Verbale interno 2024-06-03
Argo-swe/Docs pull request #104
Opened 2024-06-05 11:18 UTC by RaulPianon

[ARGO-118]

2024-06-05 11:19 UTC, RaulPianon commented
Ho aggiunto anche la firma interna di Martina che però è da sistemare

2024-06-09 20:57 UTC, RaulPianon commented
Mancano i ticket delle attività

2024-06-13 12:03 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/capitolo-riunione.tex
> +Per finire il gruppo ha stabilito che, per i prossimi \glossario{sprint}, i membri dei ruoli uscenti definiranno le attività per i membri entranti con tanto di descrizione dell'attività su \glossario
```suggestion
Il gruppo ha stabilito che, per i prossimi \glossario{sprint}, i membri che cambieranno ruolo nel passaggio da uno \glossario{sprint} a quello successivo definiranno le attività per i membri che inizieranno lo \glossario{sprint} successivo aventi quello specifico ruolo. Sarà quindi di competenza dei membri con i ruoli uscenti definire le attività e le loro descrizioni su \glossario{Jira} e sarà il Responsabile ad assegnarle o modificarle se necessario. Questo dovrebbe permettere di avanzare con più precisione e coerenza nell'andamento delle attività e avere una maggiore coordinazione. 
```

2024-06-18 19:19 UTC, martinaamico requested changes

2024-06-18 19:19 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/capitolo-riunione.tex
> +	\item Pianificazione di un incontro con la Proponente per la fine del prossimo glossario{sprint};
```suggestion
	\item Pianificazione di un incontro con la Proponente per la fine del prossimo \glossario{sprint};
```

2024-06-18 19:19 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/capitolo-riunione.tex
> +\par Il gruppo si è ritrovato come concordato per una retrospettiva dello \glossario{sprint} 4, vista esserne prossima la fine. Vengono individuate alcune le attività principali per lo \glossario{spr
```suggestion
\par Il gruppo si è ritrovato come concordato per una retrospettiva dello \glossario{sprint} 4, vista esserne prossima la fine. Vengono individuate poi alcune le attività principali per lo \glossario{sprint} successivo. 
```

2024-06-18 19:19 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/capitolo-riunione.tex
> +Viene inoltre riproposto al gruppo di organizzare i prossimi due \glossario{sprint} in modo che la loro durata sia di dieci giorni o una settimana.
```suggestion
Viene inoltre riproposto dal gruppo di organizzare i prossimi due \glossario{sprint} in modo che la loro durata sia di dieci giorni o una settimana. 
```

2024-06-18 19:19 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/firma_interna.tex
> +    %\node [anchor = south east] at (\textwidth- -1cm,-1.3cm) {\includegraphics[width=8cm]{\ModelAssets{signatures/firma_martina.png}}};
```suggestion
    \node [anchor = south east] at (\textwidth- -1cm,-1.3cm) {\includegraphics[width=8cm]{\ModelAssets{signatures/firma_martina.png}}}; 
```

2024-06-18 19:19 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-03/registro_modifiche.tex
> +		0.0.1 & 2024-05-23 & \raul & \martina & Stesura del documento \\
```suggestion
1.0.0 & 2024-05-26 & \martina &  & Approvazione del documento \\
		\hline 0.0.1 & 2024-05-23 & \raul & \martina & Stesura del documento \\
```

2024-06-23 15:23 UTC, martinaamico approved these changes

2024-06-23 15:23 UTC, merged