Preventivo spirnt 5
Argo-swe/Docs pull request #108
Opened 2024-06-06 10:21 UTC by martinaamico

Aggiunta preventivo sprint 5

2024-06-06 11:23 UTC, Rikicavaz77 commented on sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-5.tex
> +Durante lo \glossario{sprint} precedente sono state approfondite ulteriormente le tecnologie di \glossario{Flask} e \glossario{Vue.js} che durante questo sprint saranno usati in sinergia per integrar
```suggestion
Durante lo \glossario{sprint} precedente, il team ha approfondito ulteriormente i framework \glossario{Flask} e \glossario{Vue.js}, che nel corso di questo sprint saranno utilizzati in sinergia per integrare \glossario{front-end} e \glossario{back-end}.
```

2024-06-06 11:26 UTC, Rikicavaz77 commented on sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-5.tex
> +  \item Aggiornamento del \PdP con particolare attenzione sul preventivo a finire dello sprint 4 e la redistribuzione delle ore per ruolo;
```suggestion
  \item Aggiornamento del \PdP\ con particolare attenzione sul preventivo a finire dello sprint 4 e la redistribuzione delle ore per ruolo;
```

2024-06-06 11:26 UTC, Rikicavaz77 commented on sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-5.tex
> +  \item Ampliamento dei casi d'uso nell' \AdR con estensioni ed errori ed inserimento dei grafici dei \glossario{casi d'uso} rimanenti;
```suggestion
  \item Ampliamento dei casi d'uso nell'\AdR\ con estensioni ed errori ed inserimento dei grafici dei \glossario{casi d'uso} rimanenti;
```

2024-06-06 16:00 UTC, CristoMarco requested changes

2024-06-06 16:00 UTC, CristoMarco commented on sources/documents/2_RTB/PianoDiProgetto/Preventivo/Sprint/sprint-5.tex
> +Di seguito è riportato il preventivo economico del quarto \glossario{sprint}:
```suggestion
Di seguito è riportato il preventivo economico del quinto \glossario{sprint}:
```

2024-06-07 09:33 UTC, CristoMarco approved these changes
Tutto corretto.

2024-06-07 09:33 UTC, merged