Ampliamento AdR [casi d'uso, grafici e requisiti]
Argo-swe/Docs pull request #114
Opened 2024-06-11 14:36 UTC by Rikicavaz77

[ARGO-122]

[ARGO-124]

- [x] Rivedere i casi d'uso e i grafici già inseriti;
- [x] Aggiungere casi d'uso e grafici;
- [x] Aggiungere requisiti funzionali e di vincolo.

[ARGO-122]: https://argo-swe-2.atlassian.net/browse/ARGO-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ARGO-124]: https://argo-swe-2.atlassian.net/browse/ARGO-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ARGO-123]

[ARGO-123]: https://argo-swe-2.atlassian.net/browse/ARGO-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ARGO-152]

[ARGO-152]: https://argo-swe-2.atlassian.net/browse/ARGO-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ARGO-129]

[ARGO-129]: https://argo-swe-2.atlassian.net/browse/ARGO-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ARGO-121]

[ARGO-121]: https://argo-swe-2.atlassian.net/browse/ARGO-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-12 16:41 UTC, Rikicavaz77 commented
Aggiunto caso d'uso selezione DBMS.

2024-06-13 09:10 UTC, Rikicavaz77 commented
- [ ] Aggiunti requisiti di qualità;
- [ ] Aggiunti requisiti di vincolo/dominio.

2024-06-13 16:08 UTC, martinaamico requested changes

2024-06-13 16:08 UTC, martinaamico commented on sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
> +  \textbf{RV.O.5} & Il dizionario dati in formato JSON deve rispettare una struttura predefinita. & Verbale Interno \\
```suggestion
  \textbf{RV.O.5} & Il \glossario{dizionario dati} in formato JSON deve rispettare una struttura predefinita. & Verbale Interno \\
```

2024-06-13 16:08 UTC, martinaamico commented on sources/documents/2_RTB/AnalisiDeiRequisiti/requisiti.tex
> +  \textbf{RV.O.6} & La dimensione del file JSON utilizzato come dizionario dati deve essere inferiore a 1MB & Verbale Interno \\
```suggestion
  \textbf{RV.O.6} & La dimensione del file JSON utilizzato come \glossario{dizionario dati} deve essere inferiore a 1MB & Verbale Interno \\
```

2024-06-13 16:08 UTC, martinaamico commented on sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc26.tex
> +Il Tecnico seleziona un \glossario{DBMS} tra quelli disponibili, da utilizzare per la generazione del \glossario{prompt} e la conseguente costruzione della query SQL tramite \glossario{LLM}.
```suggestion
Il Tecnico seleziona un \glossario{DBMS} tra quelli disponibili, da utilizzare per la generazione del \glossario{prompt} e la conseguente costruzione della \glossario{quary} SQL tramite \glossario{LLM}.
```

2024-06-13 16:20 UTC, Rikicavaz77 commented
@martinaamico nella tabella dei requisiti eviterei di mettere troppi elementi nel glossario; altrimenti si perde in leggibilità. Magari possiamo segnare gli elementi solo alla prima occorrenza.

2024-06-13 16:38 UTC, Rikicavaz77 commented
- [ ] aggiunta requisiti funzionali;
- [ ] aggiunta caso d'uso pulizia chat;
- [ ] revisione casi d'uso;
- [ ] aggiunta grafici.

2024-06-14 16:09 UTC, Rikicavaz77 commented
- [ ] Ridefinire requisiti di qualità

2024-06-14 17:02 UTC, Rikicavaz77 commented
- [ ] Revisione caso d'uso debug e log

2024-06-15 07:17 UTC, Rikicavaz77 commented
- [ ] Aggiunto grafici uc27 (eliminazione cronologia della chat).

2024-06-18 19:00 UTC, martinaamico submitted a review, later dismissed

2024-06-18 19:00 UTC, martinaamico commented on sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc8.tex
> +L'Utente desidera copiare il \glossario{prompt} generato, con l'obiettivo di effettuare un'operazione di "Copy and Paste", incollando il contenuto del prompt in un servizio esterno che implementi \gl
```suggestion
L'Utente desidera copiare il \glossario{prompt} generato, con l'obiettivo di effettuare un'operazione di "Copy and Paste", incollando il contenuto del \glossario{prompt} in un servizio esterno che implementi \glossario{LLM}.
```

2024-06-18 19:00 UTC, martinaamico commented on sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc8.tex
> +  \item Negli appunti di sistema viene salvata una copia del \glossario{prompt}, che può essere fornita in input a un LLM esterno per la generazione di una \glossario{query} SQL.
```suggestion
  \item Negli appunti di sistema viene salvata una copia del \glossario{prompt}, che può essere fornita in input a un \glossario{LLM} esterno per la generazione di una \glossario{query} SQL.
```

2024-06-18 19:53 UTC, Rikicavaz77 commented on sources/documents/2_RTB/AnalisiDeiRequisiti/usecase/uc5.tex
> +L'Utente desidera ricevere un \glossario{prompt} da fornire in input a un modello di AI esterno al fine di ottenere una \glossario{query} SQL.
lo inserirei nel glossario

2024-06-19 17:32 UTC, Rikicavaz77 commented
- [ ] Revisione caso d'uso visualizzazione lista dizionari dati.

2024-06-23 07:41 UTC, RaulPianon approved these changes
LGTM

2024-06-23 07:52 UTC, merged