Verbale interno 2024-06-22
Argo-swe/Docs pull request #125
Opened 2024-06-24 14:09 UTC by RaulPianon

Prima stesura del verbale [ARGO-161]

2024-06-24 14:56 UTC, stoccotommaso02 commented
La struttura e il contenuto sono adeguati, una volta configurati i ticket su Jira possiamo aggiungerli

2024-06-25 06:54 UTC, mzecchinato requested changes
LGTM

2024-06-25 06:54 UTC, mzecchinato commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-06-22/capitolo-riunione.tex
> +\par Il gruppo si è incontrato inizialmente per esaminare le modifiche fatte dall'analista al documento di \AdR. Le modifiche consistono prevalentemente in una rivisitazione e sistemazione completa d
```suggestion
\par Il gruppo si è incontrato inizialmente per esaminare le modifiche fatte dall'analista al documento di \AdR. Le modifiche consistono prevalentemente in una rivisitazione e sistemazione completa del documento, dove sono state applicate le correzioni evidenziate durante l'incontro con il Professor Riccardo Cardin. Sono stati inoltre aggiunti casi d'uso che riguardano le interazioni tra l'Utente e l'interfaccia dell'applicativo.
```

2024-06-25 19:52 UTC, mzecchinato commented
aspettiamo i TODO per l'appve giusto?

2024-06-30 08:33 UTC, RaulPianon commented
> @RaulPianon aspettiamo i TODO per approvare giusto?

Sì devo solo capire quali inserire, perché sono da spartire tra questo e quello del 15 di verbale

2024-06-30 10:15 UTC, mzecchinato approved these changes
LGTM

2024-07-06 07:20 UTC, stoccotommaso02 approved these changes

2024-07-06 07:21 UTC, merged