Aggiunta sezione test al PdQ
Argo-swe/Docs pull request #126
Opened 2024-06-24 15:52 UTC by Rikicavaz77

2024-06-30 17:05 UTC, Rikicavaz77 commented
Todo:

- [ ] Controllare tabelle di tracciamento.

2024-07-02 14:36 UTC, mzecchinato requested changes
LGTM

2024-07-02 14:36 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/test/test_accettazione.tex
> +		\hline TA.2 & Verificare che l'Utente possa salvare un nuovo \glossario{dizionario dati} nel sistema:
```suggestion
		\hline TA.2 & Verificare che il Tecnico possa salvare un nuovo \glossario{dizionario dati} nel sistema:
```

2024-07-02 14:36 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/test/test_accettazione.tex
> +		\hline TA.3 & Verificare che l'Utenta possa visualizzare la lista dei dizionari caricati nel sistema:
```suggestion
		\hline TA.3 & Verificare che il Tecnico possa visualizzare la lista dei dizionari caricati nel sistema:
```
la parte dell'utente è già su TA.10

2024-07-02 14:44 UTC, mzecchinato approved these changes
LGTM

2024-07-02 14:45 UTC, merged