Glossario (termini e definizioni)
Argo-swe/Docs pull request #129
Opened 2024-06-25 14:58 UTC by Rikicavaz77

2024-06-25 19:49 UTC, mzecchinato requested changes
Aggiungerei anche che mi ero segnato 

DTO
DTO è l’acronimo di Data Transfer Object, è un design pattern usato per trasferire dati
tra sottosistemi di un’applicazione software.

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/s.tex
> +La Sentence Similarity, o similarità tra frasi, è una misura che quantifica il grado di somiglianza tra due frasi o segmenti di testo. Questo concetto è ampiamente utilizzato nell'ambito del Natural
```suggestion
La Sentence Similarity, o similarità tra frasi, è una misura che quantifica il grado di somiglianza tra due frasi o segmenti di testo. Questo concetto è ampiamente utilizzato nell'ambito del Natural Language Processing (NLP) per valutare quanto due frasi siano semanticamente simili o correlate. Le tecniche per calcolare la similarità tra frasi possono variare a seconda del contesto e degli obiettivi specifici, ma spesso coinvolgono l'uso di modelli di \glossario{embedding} del linguaggio naturale per rappresentare le frasi in spazi vettoriali e misurare la distanza o la similarità tra i loro vettori rappresentativi.
```
blocca la compilazione

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/s.tex
> +Lo Sprint è un periodo di tempo definito e limitato all'interno di uno sviluppo \glossaio{Agile} durante il quale viene svolto un lavoro specifico e concreto. Solitamente ha una durata fissa, tipicam
```suggestion
Lo Sprint è un periodo di tempo definito e limitato all'interno di uno sviluppo \glossario{Agile} durante il quale viene svolto un lavoro specifico e concreto. Solitamente ha una durata fissa, tipicamente da una a quattro settimane, durante le quali il team di sviluppo si impegna a completare un insieme di attività pianificate. Gli Sprint sono caratterizzati da obiettivi chiari e misurabili e terminano con la consegna di un incremento di lavoro funzionante. Durante uno Sprint, il lavoro viene suddiviso in attività più piccole, chiamate backlog items, e il progresso viene monitorato attraverso riunioni quotidiane chiamate Daily Scrum o Stand-up.
```
blocca la compilazione

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/c.tex
> +Un commit è un'operazione in un sistema di controllo versione che salva le modifiche apportate al codice sorgente o ai documenti in un repository. Rappresenta una "istantanea" dello stato del progett
```suggestion
Un commit è un'operazione in un sistema di controllo versione che salva le modifiche apportate al codice sorgente o ai documenti in un repository. Rappresenta una "istantanea" dello stato del progetto in un determinato momento, accompagnata da un messaggio che descrive le modifiche effettuate. Il commit permette di tracciare la storia delle modifiche, facilitando il lavoro collaborativo e il mantenimento del codice, consentendo di tornare a versioni precedenti se necessario.
```

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/d.tex
> +Un dizionario dati è una raccolta di metadati che descrive la struttura, le caratteristiche e le relazioni dei dati all'interno di un \glossario{database}. Include informazioni come: i nomi delle tab
```suggestion
Un dizionario dati è una raccolta di metadati che descrive la struttura, le caratteristiche e le relazioni dei dati all'interno di un \glossario{database}. Include informazioni come: i nomi delle tabelle e le loro descrizioni, i nomi dei campi e le loro descrizioni, i tipi di dati, le dimensioni e le relazioni tra tabelle. Questo strumento in ChatSQL serve agli utenti per comprendere quali tipi di richieste possono essere fatte al sistema e ai tecnici per comprendere il debug del sistema.
```

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/d.tex
> +Docker è una piattaforma open-source per la creazione, la distribuzione e l'esecuzione di applicazioni in contenitori leggeri e portabili. I contenitori Docker consentono agli sviluppatori di isolare
```suggestion
Docker è una piattaforma open-source per la creazione, la distribuzione e l'esecuzione di applicazioni in contenitori leggeri e portabili. I contenitori Docker consentono agli sviluppatori di eseguire le proprie applicazioni e le relative dipendenze in un ambiente isolato, garantendo che esse funzionino in modo consistente su qualsiasi sistema operativo o infrastruttura. Docker facilita la distribuzione delle applicazioni, permettendo agli sviluppatori di racchiudere il proprio codice insieme a tutte le librerie e le dipendenze necessarie, eliminando così i problemi di compatibilità tra ambienti di sviluppo e produzione.
```

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/e.tex
> +Nel contesto dell'elaborazione del linguaggio naturale, l'embedding si riferisce alla rappresentazione numerica di parole o frasi in uno spazio vettoriale continuo. Gli embedding sono creati utilizza
che sia il caso di aggiungere "Sentiment" al glossario?

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/g.tex
> +\subsection*{GHCR}
```suggestion
\subsection*{GHCR}
TODO
```

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/g.tex
>  \subsection*{Google Docs}
```suggestion
\subsection*{Google Drive}
```

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/g.tex
>  \subsection*{Google Docs}
si parla sia di docs, sheet e presentazioni

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/r.tex
> +\subsection*{Relase}
```suggestion
\subsection*{Release}
```

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/s.tex
> +\subsection*{Stackeholders}
```suggestion
\subsection*{Stakeholders}
```

2024-06-25 19:49 UTC, mzecchinato commented on sources/documents/2_RTB/Glossario/Lettere/f.tex
```suggestion
\vspace{2em}
\subsection*{FastAPI}
TODO

```

2024-06-30 07:42 UTC, Rikicavaz77 commented on sources/documents/2_RTB/Glossario/Lettere/e.tex
> +Nel contesto dell'elaborazione del linguaggio naturale, l'embedding si riferisce alla rappresentazione numerica di parole o frasi in uno spazio vettoriale continuo. Gli embedding sono creati utilizza
non l'abbiamo mai usato più che altro.

2024-06-30 10:19 UTC, mzecchinato approved these changes
LGTM

2024-06-30 11:07 UTC, merged