Consuntivo Sprint 6
Argo-swe/Docs pull request #132
Opened 2024-06-29 17:44 UTC by LewentalDigital

2024-06-30 12:49 UTC, Rikicavaz77 requested changes

2024-06-30 12:49 UTC, Rikicavaz77 commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
> +      Cristo Marco & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
Questa è vuota.

2024-06-30 17:42 UTC, RaulPianon requested changes
Viste le modifiche alle tabelle immagino siano anche da reinserire i grafici

2024-06-30 17:42 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
> +      Amministratore & 6 & 2 & 120,00 & 40,00 \\ \hline
```suggestion
      Amministratore & 7 & 1 & 140,00 & 20,00 \\ \hline
```
Non so se sia un errore o qualcuno che ha compilato dopo che hai fatto questa tabella, ma il consuntivo economico del sesto sprint ha questi valori per l'amministratore

2024-06-30 17:42 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
> +      Analista & 4 & 2 & 100,00 & 50,00 \\ \hline
```suggestion
      Analista & 5 & 1 & 125,00 & 25,00 \\ \hline
```

2024-06-30 17:42 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
> +      Verificatore & 3 & 1 & 45,00 & 15,00 \\ \hline
```suggestion
      Verificatore & 4 & 0 & 60,00 & 0,00 \\ \hline
```

2024-06-30 17:42 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
> +      \textbf{Totale} & \textbf{25} & 5 & \textbf{505,00} & 90,00 \\ \hline
```suggestion
      \textbf{Totale} & \textbf{28} & 2 & \textbf{565,00} & 30,00 \\ \hline
```

2024-06-30 17:42 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
> +      \textbf{Restante} & 383 & / & 7.575,00 & / \\ \hline
```suggestion
      \textbf{Restante} & 380 & / & 7.515,00 & / \\ \hline
```

2024-06-30 17:42 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
> +        Cristo Marco & 2 & 10 & 2 & 17 & 10 & 15 & 56 \\
```suggestion
        Cristo Marco & 2 & 9 & 1 & 17 & 10 & 14 & 53 \\ 
```

2024-06-30 17:42 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-6.tex
> +        \textbf{Totale ore per ruolo} & 29 & 33 & 16 & 107 & 97 & 101 & \textbf{383} \\
```suggestion
        \textbf{Totale ore per ruolo} & 29 & 32 & 15 & 107 & 97 & 100 & \textbf{380} \\ 
```

2024-07-01 18:03 UTC, Rikicavaz77 requested changes

2024-07-01 18:36 UTC, Rikicavaz77 approved these changes
LGTM

2024-07-01 18:36 UTC, merged