aggiunta pianificazione e preventivo spint 7
Argo-swe/Docs pull request #135
Opened 2024-07-02 15:28 UTC by mzecchinato

aggiunta sezione sprint 7 per preventivo e pianificazione

2024-07-03 12:13 UTC, LewentalDigital commented on sources/documents/2_RTB/PianoDiProgetto/Preventivo/preventivo.tex
> +\par Il rendimento complessivo per ciascun componente è di 91 ore, ripartite equamente nei ruoli di progetto, per un totale di 637 ore produttive. L'uniformità nella distribuzione dei ruoli tra i mem
```suggestion
\par Il rendimento complessivo per ciascun componente è di 92 ore, ripartite equamente nei ruoli di progetto, per un totale di 644 ore produttive. L'uniformità nella distribuzione dei ruoli tra i membri del team viene mantenuta procedendo a rotazione, affinché ogni risorsa possa esplorare tutte le mansioni. Al fine di migliorare la leggibilità e la compattezza delle tabelle, i ruoli di progetto sono identificati dalle seguenti \glossario{abbreviazioni}:
```
Avevamo deciso di aumentare di un'ora un po di tempo fa, mi sono accorto ora che non è stato aggiornato questo file

2024-07-03 12:18 UTC, LewentalDigital commented on sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-7.tex
> +Il team in vista della RTB si appresta a concludere le attività di programmazione relative al \glossario{PoC} e nell'ultimare le sezioni incomplete dei documenti, in modo da porre maggiore prima dell
```suggestion
Il team in vista della RTB si appresta a concludere le attività di programmazione relative al \glossario{PoC} e nell'ultimare le sezioni incomplete dei documenti, focalizzandosi maggiormente sulla sezione documentale  prima della consegna.
```
Non riesco a capire, forse intendevi dire questo?

2024-07-03 12:25 UTC, LewentalDigital commented on sources/documents/2_RTB/PianoDiProgetto/registro_modifiche.tex
>  		0.1.6 & 2024-06-24 & \sebastiano & \marco, \mattia, \tommaso & Stesura del preventivo \glossario{sprint} 6 \\
```suggestion
		\hline 0.1.6 & 2024-06-24 & \sebastiano & \marco, \mattia, \tommaso & Stesura del preventivo \glossario{sprint} 6 \\
```

2024-07-04 06:57 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiProgetto/Pianificazione/Sprint/sprint-7.tex
> +Il team in vista della RTB si appresta a concludere le attività di programmazione relative al \glossario{PoC} e nell'ultimare le sezioni incomplete dei documenti, in modo da porre maggiore prima dell
si era "in modo di porre maggiore attenzione ...", ma si è perso nella mia testa. Meglio la tua

2024-07-07 14:11 UTC, RaulPianon commented
@mzecchinato mi sono accorto che nel cosnuntivo dello sprint 7 ho segnato 3 ore e mezza da analista, ma in realtà erano di Programmatore. Cambio sia sul foglio di calcolo e ti richiedo la modifica qua o lasciamo stare?

2024-07-07 14:12 UTC, mzecchinato commented
> @mzecchinato mi sono accorto che nel cosnuntivo dello sprint 7 ho segnato 3 ore e mezza da analista, ma in realtà erano di Programmatore. Cambio sia sul foglio di calcolo e ti richiedo la modifica qua o lasciamo stare?

Segna pure poi quando hai fatto faccio la modifica

2024-07-07 14:19 UTC, RaulPianon requested changes

2024-07-07 14:19 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
> +      Cavalli Riccardo & 0 & 0 & 0 & 0 & 0 & 0 & 5 \\
```suggestion
      Cavalli Riccardo & 0 & 0 & 0 & 0 & 3 & 2 & 5 \\
```

2024-07-07 14:19 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
> +      Amministratore & 11 & -4 & 240,00 & -80,00 \\ \hline
```suggestion
      Amministratore & 12 & -4 & 240,00 & -80,00 \\ \hline
```

2024-07-07 14:19 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
> +        \textbf{Totale ore per ruolo} & 25 & 21 & 15 & 107 & 89 & 86 & \textbf{353} \\
```suggestion
        \textbf{Totale ore per ruolo} & 25 & 21 & 15 & 107 & 89 & 96 & \textbf{353} \\
```

2024-07-07 14:28 UTC, mzecchinato commented
@RaulPianon vedo che hai 3,5 ore come amministratore (non analista) le sposto a Pr su excel e aggiorno?

2024-07-07 14:29 UTC, RaulPianon commented
> > @mzecchinato mi sono accorto che nel cosnuntivo dello sprint 7 ho segnato 3 ore e mezza da analista, ma in realtà erano di Programmatore. Cambio sia sul foglio di calcolo e ti richiedo la modifica qua o lasciamo stare?
> 
> Segna pure poi quando hai fatto faccio la modifica

Ho fatto. Nel caso dimmi se vuoi una mano per modificare perché immagino sia anche da riscaricare i grafici ecc...

2024-07-07 14:30 UTC, mzecchinato commented
> > > @mzecchinato mi sono accorto che nel cosnuntivo dello sprint 7 ho segnato 3 ore e mezza da analista, ma in realtà erano di Programmatore. Cambio sia sul foglio di calcolo e ti richiedo la modifica qua o lasciamo stare?
> > 
> > 
> > Segna pure poi quando hai fatto faccio la modifica
> 
> Ho fatto. Nel caso dimmi se vuoi una mano per modificare perché immagino sia anche da riscaricare i grafici ecc...

tranquillo, ti metto le ore 3+1 invece che 0,5+3,5 perchè poi i conteggi li facciamo interi

2024-07-08 19:39 UTC, RaulPianon submitted a review, later dismissed
C'è solo una riga sbagliata della tabella nel consuntivo: non ho capito se è stata cambiata o se non l'ho vista io l'altra volta. Adesso controllo anche i pdf

2024-07-08 19:39 UTC, RaulPianon commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
> +      Dall’Amico Martina & 0 & 2 & 0 & 0 & 0 & 1 & 3 \\
```suggestion
      Dall’Amico Martina & 0 & 0 & 0 & 0 & 3 & 0 & 3 \\
```
Non so se è cambiato dall'ultima volta, ma è segnato così

2024-07-08 19:44 UTC, RaulPianon commented
I grafici mi sembrano apposto perché il resto della tabella era corretto (anche le somme finali)

2024-07-08 20:01 UTC, Rikicavaz77 commented on sources/documents/2_RTB/PianoDiProgetto/Consuntivo/Sprint/sprint-7.tex
> +      Dall’Amico Martina & 0 & 2 & 0 & 0 & 0 & 1 & 3 \\
sistemo io

2024-07-09 06:51 UTC, mzecchinato commented
ma è cambiato qualcosa? avevo controllato i valori

2024-07-09 06:52 UTC, Rikicavaz77 commented
> ma è cambiato qualcosa? avevo controllato i valori

ho cambiato giusto due cose, perché alcuni stavano finendo le ore da programmatori

2024-07-09 16:38 UTC, Rikicavaz77 approved these changes
LGTM

2024-07-09 16:39 UTC, merged