Cruscotto di valutazione della qualità
Argo-swe/Docs pull request #140
Opened 2024-07-05 14:04 UTC by Rikicavaz77

2024-07-07 13:52 UTC, mzecchinato commented
aggiunte descrizioni metriche mancanti per
- efficienza contromisure
- efficienza temporale
- metriche soddisfatte

2024-07-08 08:04 UTC, Rikicavaz77 commented
> aggiunte descrizioni metriche mancanti

Perfetto, tra poco controllo e questa pull request direi che si può chiudere. Poi ne apriremo un'altra magari mercoledì per ricaricare alcuni grafici aggiornati.

2024-07-16 13:19 UTC, mzecchinato requested changes
LGTM
Ho solo messo i succerimenti per allineare i valore di intervallo dove non è 100%

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
> +  \item Metriche del software: \\ \href{https://learn.microsoft.com/en-us/visualstudio/code-quality/code-metrics-values?view=vs-2022}{https://learn.microsoft.com/en-us/visualstudio/code-quality/code-
link esce dalla pagina

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
> +  \item Standard ISO/IEC 90003: \\ \href{https://cdn.standards.iteh.ai/samples/35867/36860aa4caba4c84b26051db576456d3/ISO-IEC-90003-2004.pdf}{https://cdn.standards.iteh.ai/samples/35867/36860aa4caba4
link esce dalla pagina

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_per_obiettivo.tex
> +    \hline M.PD.18 & Percentuale di test superati & 80\% & 100\% \\
```suggestion
    \hline M.PD.18 & Percentuale di test superati & $\geq$ 80\% & 100\% \\
```

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_per_obiettivo.tex
>      M.PD.4 & Indice Gulpease & 50\% & $\geq$ 80\% \\
```suggestion
    M.PD.4 & Indice Gulpease & $\geq$ 50\% & $\geq$ 80\% \\
```

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_per_obiettivo.tex
> +		\hline M.PD.6 & Browser supportati & 80\% & 100\% \\
```suggestion
		\hline M.PD.6 & Browser supportati & $\geq$ 80\% & 100\% \\
```

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_per_obiettivo.tex
> +    \hline M.PD.20 & Tolleranza agli errori & 70\% & 100\% \\
```suggestion
    \hline M.PD.20 & Tolleranza agli errori & $\geq$ 70\% & 100\% \\
```

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/metriche/tabelle_metriche_prodotto.tex
> +		\hline M.PD.6 & Browser supportati & 80\% & 100\% \\
```suggestion
		\hline M.PD.6 & Browser supportati & $\geq$ 80\% & 100\% \\
```

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/test/checklist/errori_formali.tex
> +    \hline Back-end e backend (front-end e frontend) & Si possono utilizzare entrambe le forme, con o senza trattino.\\
```suggestion
    \hline Back-end/backend e front-end/frontend & Si possono utilizzare entrambe le forme, con o senza trattino.\\
```

2024-07-16 13:19 UTC, mzecchinato commented on sources/documents/2_RTB/PianoDiQualifica/test/test_accettazione.tex
> +		\hline TA.3 & Verificare che il Tecnico possa visualizzare la lista dei dizionari dati caricati nel sistema:
```suggestion
		\hline TA.3 & Verificare che il Tecnico possa visualizzare la lista dei \glossario{dizionari dati} caricati nel sistema:
```

2024-07-16 13:27 UTC, Rikicavaz77 commented on sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
> +  \item Metriche del software: \\ \href{https://learn.microsoft.com/en-us/visualstudio/code-quality/code-metrics-values?view=vs-2022}{https://learn.microsoft.com/en-us/visualstudio/code-quality/code-
Risolvo.

2024-07-16 13:27 UTC, Rikicavaz77 commented on sources/documents/2_RTB/PianoDiQualifica/introduzione.tex
> +  \item Standard ISO/IEC 90003: \\ \href{https://cdn.standards.iteh.ai/samples/35867/36860aa4caba4c84b26051db576456d3/ISO-IEC-90003-2004.pdf}{https://cdn.standards.iteh.ai/samples/35867/36860aa4caba4
Risolvo.

2024-07-16 14:18 UTC, merged