Verbale Esterno 2024-07-09
Argo-swe/Docs pull request #147
Opened 2024-07-10 10:36 UTC by RaulPianon

[ARGO-210]

Serve una revisione soprattutto sull'ultima parte. In più mancano le attività

2024-07-10 11:14 UTC, stoccotommaso02 requested changes

2024-07-10 11:14 UTC, stoccotommaso02 commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\par La Proponente chiede se il gruppo è pronto per affrontare la prima revisione e suggerisce che ogni membro si prepari qualcosa da dire o esporre, durante la revisione. Inoltre consiglia di effett
```suggestion
\par La Proponente chiede se il gruppo è pronto per affrontare la prima revisione e suggerisce che ogni membro si prepari qualcosa da dire o esporre, durante la revisione. Inoltre rimarca l'utilità di effettuare più test su \glossario{database}, sfruttandone uno in locale.
```

2024-07-10 11:14 UTC, stoccotommaso02 commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\par La Proponente chiede se il gruppo è pronto per affrontare la prima revisione e suggerisce che ogni membro si prepari qualcosa da dire o esporre, durante la revisione. Inoltre consiglia di effett
Rifrasato in quanto riferimento alla discussione avuta in precedenza

2024-07-10 11:14 UTC, stoccotommaso02 commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\textbf{Risposta:} Sì, è normale. I \glossario{database} hanno modi di scrivere diversi, come ad esempio il segno di "diverso da" che in alcuni viene presentato in stile "SQL" e in altri in stile "C+
```suggestion
\textbf{Risposta:} Sì, è normale. I \glossario{database} hanno modi di scrivere diversi, come ad esempio il segno di "diverso da" che in alcuni viene presentato in stile "SQL" e in altri in stile "C++": la disuguaglianza quindi ad esempio, può essere motivo di confusione per il modello che procede a cercare quali \glossario{database} usano quella notazione e scrive altre informazioni di conseguenza. Anche l'utilizzo di "LIKE" rispetto a controlli di uguaglianza stretta sono adeguati, in quanto meno stringenti nel confronto tra stringhe.
```

2024-07-10 11:14 UTC, stoccotommaso02 commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\par \textbf{Domanda:} Il Professor Cardin ci ha detto che è necessario avere una notazione quando un \glossario{database} è indicizzato. Lei cosa ne pensa a riguardo? Pensa sia necessario? \\
```suggestion
\par \textbf{Domanda:} Nel considerare la performance di una query abbiamo considerato se agiungere una notazioneper descrivere gli indici di un \glossario{database}. Lei cosa ne pensa a riguardo? Ritiene sia necessario? \\
```

2024-07-10 11:14 UTC, stoccotommaso02 commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\textbf{Risposta:} Non è necessario, poiché avendo quest'informazione l'unica cosa che cambia è la struttura e non la correttezza delle query, che è quello che chiediamo al fine del progetto.
```suggestion
\textbf{Risposta:} Non è necessario, poiché avendo quest'informazione l'unica cosa che cambia è la struttura e non la correttezza delle query, che è quello che chiediamo al fine del progetto. Va considerato inoltre il rischio che aggiungere l'informazione nel prompt lo "inquini", inducendo il Large Language Model a query meno corrette.
```

2024-07-10 11:14 UTC, stoccotommaso02 commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/local.tex
> +	Il gruppo ha organizzato un incontro con la Proponente per esporle il lavoro svolto nelle ultime settimane e presentare la versione del Proof of Concept che verrà portata alla \RTB.
```suggestion
	Il gruppo ha organizzato un incontro con la Proponente per esporre il lavoro svolto nelle ultime settimane e presentare la versione del Proof of Concept che verrà portata alla \RTB.
```

2024-07-10 11:15 UTC, martinaamico submitted a review, later dismissed

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +Da qui viene incollato una richiesta sufficientemente complessa che genera un \glossario{prompt} e viene mostrato il risultato ottenuto.
```suggestion
Successivamente viene incollato una richiesta preselezionata dal team e sufficientemente complessa che genera un \glossario{prompt} e viene mostrato il risultato ottenuto.
```

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\par La Proponente trova interessante il risultato ottenuto da \glossario{ChatGPT}, in particolare l'utilizzo di un NOT EXIST e che la query risultato fosse abbastanza ridotta. Il gruppo commenta oss
```suggestion
\par La \glossario{Proponente} trova interessante il risultato ottenuto da \glossario{ChatGPT}, in particolare l'utilizzo di un NOT EXIST e che la query risultato fosse abbastanza ridotta. Il gruppo commenta osservando che, dai test svolti, \glossario{ChatGPT} sembri essere quello che ritorna le  \glossario{query} più ridotte.
```

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +La Proponente chiede di testare il \glossario{prompt} su altri modelli, utilizzando \glossario{LMsys}. Vengono svolti test diversi con modelli che propongono risultati simili, ma con delle divergenze
```suggestion
La \glossario{Proponente} chiede di testare il \glossario{prompt} su altri modelli, utilizzando \glossario{LMsys}. Vengono svolti test diversi con modelli che propongono risultati simili, ma con delle divergenze nell'espressione della \glossario{query}. Ad ogni test, la \glossario{Proponente} esamina con il gruppo il significato e la correttezza delle  \glossario{query} generate, evidenziando come, di modello in modello, ci siano delle sezioni dove il modello sembra confondersi data la complessità della ricerca.
```

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +La Proponenete chiede al gruppo se sono stati svolti dei test anche su un \glossario{database} locale: il gruppo afferma di aver svolto dei test sempre con una stessa richiesta e che questa ha portat
```suggestion
La \glossario{Proponente} chiede al gruppo se sono stati svolti dei test anche su un \glossario{database} locale: il gruppo afferma di aver svolto dei test sempre con una stessa richiesta e che questa ha portato i risultati richiesti.
```

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +La Proponente evidenzia come non ci siano errori palesi, tuttavia nelle query generate si verificano situazioni che potrebbero portare a delle condizioni di errore e chiede al gruppo di svolgere più
```suggestion
La \glossario{Proponente} evidenzia come non ci siano errori strutturali evidenti nella generazione delle \glossario{query}, tuttavia da questo esempio si evince che potrebbero verificarsi condizioni di errore e viene chiesto al gruppo di svolgere più test provando con dei \glossario{database} in locale.
```

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\par Il gruppo ritorna al Proof of Concept per illustrare le funzionalità rimanenti. Viene mostrato il \glossario{debug} che illustra in un \glossario{log} i valori rilevanti e da la possibilità di s
```suggestion
\par Al termine dei test con gli LLM il gruppo ha riportato l'attenzione al Proof of Concept per illustrare le funzionalità rimanenti. Viene mostrato il \glossario{debug} che illustra in un \glossario{log} i valori rilevanti e da la possibilità di scaricarlo in un formato testuale. Inoltre viene mostrata la sezione riguardante la visualizzazione, l'aggiunta, la modifica e l'eliminazione dei \glossario{dizionari dati}.
```

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\par La Proponente chiede se il gruppo è pronto per affrontare la prima revisione e suggerisce che ogni membro si prepari qualcosa da dire o esporre, durante la revisione. Inoltre consiglia di effett
```suggestion
\par La \glossario{Proponente} chiede se il gruppo è pronto per affrontare la prima revisione e suggerisce che ogni membro si prepari qualcosa da dire o esporre, durante la revisione. Inoltre consiglia di effettuare più test su \glossario{database}, sfruttandone uno in locale.
```

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\par Il gruppo conclude con alcune domande per la Proponente in vista del Proof of Concept
```suggestion
\par Il gruppo conclude con alcune domande per la \glossario{Proponente} in vista del Proof of Concept
```

2024-07-10 11:15 UTC, martinaamico commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +\par Il gruppo conclude la riunione ringraziando la Proponente per la disponibilità. La Proponente resta in attesa di notizie sul risultato della \RTB.
```suggestion
\par Il gruppo conclude la riunione ringraziando la \glossario{Proponente} per la disponibilità. La Proponente resta in attesa di notizie sul risultato della \RTB.
```

2024-07-10 13:28 UTC, stoccotommaso02 commented on sources/documents/2_RTB/Verbali/Esterni/VerbaleEsterno_2024-07-09/capitolo-riunione.tex
> +Viene poi effettuato il logout per mostrare come l'utente interagisce con l'applicativo: viene mostrata la pagina della chat con la quale l'utente può interagire inviando richieste in linguaggio natu
```suggestion
Viene poi effettuato il logout per mostrare come l'utente interagisce con l'applicativo: viene mostrata la pagina della chat con la quale l'utente può interagire inviando richieste in linguaggio naturale per ottenere il \glossario{prompt}. Successivamente vengono mostrate le impostazioni della chat, con le quali l'utente può selezionare il \glossario{dizionario dati}, vederne un'anteprima con una descrizione delle tabelle che contiene, selezionare il \glossario{DBMS} e la lingua di inserimento.
```

2024-07-10 13:51 UTC, stoccotommaso02 approved these changes
LGTM

2024-07-11 13:58 UTC, Rikicavaz77 commented
- Sistemo alcune cose.

2024-07-11 17:07 UTC, Rikicavaz77 commented
Ho anche avanzato la versione.

2024-07-11 17:10 UTC, Rikicavaz77 commented
[Uploading VerbaleEsterno_2024-07-09.pdf…]()

2024-07-12 06:44 UTC, mzecchinato approved these changes
LGTM

2024-07-12 07:07 UTC, merged