2 rtb lettera presentazione
Argo-swe/Docs pull request #151
Opened 2024-07-10 13:07 UTC by martinaamico

2024-07-10 18:54 UTC, mzecchinato requested changes
ho caricato anche l'immagine della firma

2024-07-10 18:54 UTC, mzecchinato commented on sources/documents/2_RTB/LetteraDiPresentazione/LetteraDiPresentazione.tex
> +  Padova (PD) 2024-03-26 \\
```suggestion
  Padova (PD) 2024-07-10 \\
```
o la data che decidiamo vicina alla consegna

2024-07-10 18:54 UTC, mzecchinato commented on sources/documents/2_RTB/LetteraDiPresentazione/LetteraDiPresentazione.tex
> +proposto dall’azienda Zucchetti S.p.A. nel Capitolato C9.
```suggestion
proposto dall’azienda Zucchetti S.p.A. nel Capitolato C9. \newline
```

2024-07-10 18:54 UTC, mzecchinato commented on sources/documents/2_RTB/LetteraDiPresentazione/LetteraDiPresentazione.tex
> +      \node [anchor = south east] at (\textwidth-1cm,-0.6cm) {\includegraphics[width=5.5cm]{\ModelAssets{signatures/firma_mattia.png}}}; % Dimensioni e coordinate da variare in base a ciascuna firma
```suggestion
      \node [anchor = south east] at (\textwidth-1cm,-0.2cm) {\includegraphics[width=5.5cm]{\ModelAssets{signatures/firma_mattia.png}}}; % Dimensioni e coordinate da variare in base a ciascuna firma
```

2024-07-10 19:41 UTC, mzecchinato requested changes
Andranno aggiornate le versioni di tutti i documenti prima di generare il PDF

2024-07-10 19:41 UTC, mzecchinato commented on sources/documents/2_RTB/LetteraDiPresentazione/LetteraDiPresentazione.tex
> +    \item Piano di qualifica versione 1.0.0;
```suggestion
    \item \AnalisiDeiRequisiti;
    \item \Glossario;
    \item \NormeDiProgetto;
    \item \PianoDiProgetto;
    \item \PianoDiQualifica; 
```

2024-07-13 20:01 UTC, Rikicavaz77 commented
Le modifiche sono già state integrate nella pull request https://github.com/Argo-swe/Docs/pull/153.

2024-07-13 20:01 UTC, closed without merging