Stesura verbale del 2024-07-18
Argo-swe/Docs pull request #160
Opened 2024-07-20 08:19 UTC by RaulPianon

[ARGO-224]

2024-07-20 08:19 UTC, RaulPianon commented
Mancano un paio di attività che non hanno assegnatario e data, per il resto penso ci sia tutto

2024-07-20 09:41 UTC, Rikicavaz77 requested changes

2024-07-20 09:41 UTC, Rikicavaz77 commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/todo.tex
> +    \hline ARGO-233 & Individuazione pattern architetturali per il \glossario{back-end} & - & - \\
Queste vanno rimosse, sono nel backlog, ma non ancora uno sprint di riferimento.

2024-07-20 09:41 UTC, Rikicavaz77 commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-07-18/todo.tex
> +    \hline ARGO-233 & Individuazione pattern architetturali per il \glossario{back-end} & - & - \\
Da ARGO-230 in giù.

2024-07-21 10:10 UTC, Rikicavaz77 approved these changes
LGTM.

@LewentalDigital Lascio a te chiudere la PR dato che sei responsabile.

2024-07-22 08:52 UTC, Rikicavaz77 commented
Aggiorno la firma.

2024-07-22 11:01 UTC, LewentalDigital approved these changes

2024-07-22 11:01 UTC, merged