Progettazione dei dettaglio front end
Argo-swe/Docs pull request #180
Opened 2024-08-01 14:52 UTC by Rikicavaz77

2024-08-01 15:04 UTC, Rikicavaz77 commented
Collegata a https://github.com/Argo-swe/Docs/pull/180, ma va chiusa prima questa.

2024-08-02 07:34 UTC, mzecchinato commented
> Collegata a #180, ma va chiusa prima questa.

intendi 181?

2024-08-02 12:47 UTC, Rikicavaz77 commented
> > Collegata a #180, ma va chiusa prima questa.
> 
> intendi 181?

Si ho invertito le pull request.

2024-08-04 19:50 UTC, CristoMarco requested changes
Solo qualche errore di battitura.
Ho notato però che quando si parla di menù fuori dalla nomenclatura inglese, c'è scritto "menu" senza accento. Non l'ho corretto perché magari è voluto.

2024-08-04 19:50 UTC, CristoMarco commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Frontend/componenti.tex
> +  \item Login Form: modulo per l'inserimento delle credenziali di accesso.
```suggestion
  \item Login Form: modulo per l'inserimento delle credenziali di accesso;
```

2024-08-04 19:50 UTC, CristoMarco commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Frontend/componenti.tex
> +  \item Copy Button: pulsante per copiare il testo del messaggio negli appunti di sistema.
```suggestion
  \item Copy Button: pulsante per copiare il testo del messaggio negli Appunti di sistema.
```

2024-08-04 19:50 UTC, CristoMarco commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Frontend/componenti.tex
> +  \item Copyrigth section: sezione contenente le seguenti informazioni:
```suggestion
  \item Copyright section: sezione contenente le seguenti informazioni:
```

2024-08-04 19:52 UTC, Rikicavaz77 commented
> Solo qualche errore di battitura. Ho notato però che quando si parla di menù fuori dalla nomenclatura inglese, c'è scritto "menu" senza accento. Non l'ho corretto perché magari è voluto.

Tu lo useresti con o senza accento?

2024-08-04 21:13 UTC, CristoMarco commented
L'Accademia della Crusca dice che entrambe le forme sono legittime quindi direi che si può lasciare com'è

2024-08-04 21:13 UTC, CristoMarco approved these changes

2024-08-04 21:18 UTC, merged