Sezione DataBase - di specifiche tecniche
Argo-swe/Docs pull request #183
Opened 2024-08-02 14:36 UTC by martinaamico

2024-08-02 14:59 UTC, RaulPianon commented
[ARGO-254]
[ARGO-265]

2024-08-02 20:38 UTC, Rikicavaz77 requested changes
Manca avanzamento di versione.

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +Il diagramma utilizza la notazione standard per le descrizioni dei database relazionali, dove le entità sono rapprentate dai rettagoli mentre le relazioni sono le linee che collegano le entità. Le si
```suggestion
\par Il diagramma utilizza la notazione standard per le descrizioni dei database relazionali; le entità sono rappresentate da rettangoli, mentre le relazioni sono le linee che collegano le entità. All'interno del diagramma sono presenti le seguenti sigle:
\begin{itemize}
    \item \textbf{PK}: chiave primaria;
    \item \textbf{U}: attributi, o campi, della tabella.
\end{itemize}

\par Le linee terminano con dei simboli che ne indicano la cardinalità. Le tabelle sono inoltre collegate a un rombo che rappresenta la relazione tra di esse: questa relazione non è una tabella, ma serve solo a scopo illustrativo.
```

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +Il diagramma E-R (entità-relazione) riportato a seguito illustra la struttura e le relazioni all'interno del database.
```suggestion
\par Il diagramma E-R (entità-relazione) riportato a seguito illustra la struttura e le relazioni all'interno del database.
```

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +La tabella \textbf{Admins} contiene i seguenti campi:
```suggestion
\par La tabella \textbf{Admins} contiene i seguenti campi:
```

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +Ogni entry della tabella descrive un Admin, cioè un Tecnico che può eseguire operaizoni CRUD sui dizionari dati.
```suggestion
\par Ogni entry della tabella descrive un Admin, cioè un Tecnico che può eseguire operazioni \glossario{CRUD} sui dizionari dati.
```

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +La tabella \textbf{Dictionaries} include i seguenti campi:
```suggestion
\par La tabella \textbf{Dictionaries} include i seguenti campi:
```

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +    \item \textbf{Description}: una descrizione del dizionario, di tipo string.
```suggestion
    \item \textbf{Description}: la descrizione del dizionario, di tipo string.
```

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +Il diagramma mostra anche le operazioni CRUD (Create, Read, Update, Delete) che possono essere eseguite su queste tabelle.
```suggestion
Il diagramma mostra anche le operazioni CRUD (Create, Read, Update, Delete), ossia le interazioni tra i Tecnici e i \glossario{dizionari dati}.
```

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +    \item La relazione \textbf{0-N} : un admin può operare da 0 a N dizionari;
```suggestion
      \item Relazione \textbf{0-N}: un admin può eseguire operazioni CRUD su 0 o N dizionari;
```

2024-08-02 20:38 UTC, Rikicavaz77 commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Database/database.tex
> +    \item La notazione \textbf{1-N} : su un dizonario possono operare da 1 a N admin.
```suggestion
    \item Relazione \textbf{1-N} : un dizionario dati può essere gestito da 1 o N admin.
```

2024-08-03 12:01 UTC, Rikicavaz77 reviewed
@RaulPianon Le modifiche sono a posto, però bisogna aggiornare registro modifiche e global per avanzare di versione.

2024-08-04 20:12 UTC, RaulPianon commented
Ho aggiornato la sezione Database e l'ho resa una sottosezione di "Progettazione delle componenti" come penso dovesse essere

2024-08-04 20:27 UTC, Rikicavaz77 approved these changes
LGTM

2024-08-04 20:27 UTC, merged