Aggiunta progettazione alto livello back-end
Argo-swe/Docs pull request #190
Opened 2024-08-07 19:15 UTC by CristoMarco

2024-08-08 13:41 UTC, RaulPianon requested changes
Dalle altre parti sembra succedere ogni tanto, ma arriva prima di fine pagina. Non capisco perché lo faccia con alcune e con altre no

2024-08-08 13:41 UTC, RaulPianon commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Backend/componenti.tex
> + \item Scrive il contenuto del file in un nuovo file utilizzando \texttt{aiofiles.open(\_\_generate\_schema\_file\_name(new\_dic.id), "wb")};
Questo punto sfora e non si leggono tutti i parametri. Sarebbe da staccare e andare a capo o risolvere la cosa

2024-08-08 13:41 UTC, RaulPianon commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Backend/componenti.tex
> + \item Scrive il contenuto del file in un nuovo file utilizzando \texttt{aiofiles.open(\_\_generate\_schema\_file\_name(id), "wb")};
Anche qui la stessa cosa ed esce dalla pagina

2024-08-08 13:41 UTC, RaulPianon commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Backend/componenti.tex
> + \item Se il nome o la descrizione del dizionario sono assenti, restituisce un oggetto \texttt{DictionaryResponseDto} con \texttt{data=None}, un messaggio di errore e lo stato \texttt{ResponseStatusE
Stessa cosa qua

2024-08-08 13:41 UTC, RaulPianon commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneLogica/Backend/componenti.tex
> + \item Verifica se esiste un altro dizionario con lo stesso nome utilizzando \texttt{crud.get\_dictionary\_by\_name(db, dictionary.name)};
E qua

2024-08-08 13:42 UTC, RaulPianon commented
Dei pezzi di documento che ho indicato, intendo l'ultima riga prima del commento. Se controlli dal PDF vedi che ci sono alcuni punti dove la frase sfora e per qualche motivo non va a capo

2024-08-08 16:22 UTC, CristoMarco commented
Non capisco come risolvere.
@mzecchinato o @stoccotommaso02 per caso sapete come spezzare `\texttt` per andare accapo come il testo normale?

2024-08-08 16:39 UTC, stoccotommaso02 commented
> Non capisco come risolvere. @mzecchinato o @stoccotommaso02 per caso sapete come spezzare `\texttt` per andare accapo come il testo normale?

Il monospace è allergico ad andare a capo, tuttavia se inserisci nel contenuto il simbolo `\-` dai al compiler dei "suggerimenti" su dove andare a capo. Esempio:
`\texttt{SchemaMultiExtractor.extract\_preview(id)};` è una delle righe che va in overflow, scrivendola come
`\texttt{SchemaMultiExtractor\-.\-extract\_preview(id)};` il compiler sceglie il punto più opportuno per andare a capo (ergo: li puoi seminare un po' ovunque senza timore di andare a capo 10 volte, li utilizzerà solo qualora necessario)

2024-08-08 21:31 UTC, mzecchinato reviewed
gestirei tutti gli endpoint sotto una sezione apposita, per poi distinguere le altre parti contenute in BE (index manager, prompt manager,... )

Aggiungerei quindi solo una `\subsubsection{Endpoint} che raggruppi tutto

2024-08-08 21:33 UTC, Rikicavaz77 commented
Sempre in progettazione logica dici?

2024-08-08 21:34 UTC, Rikicavaz77 commented
Perché index manager e prompt manager sono già progettazione di dettaglio.

2024-08-09 06:26 UTC, mzecchinato commented
Ah ok, vedevo solo database al momento

2024-08-13 09:45 UTC, mzecchinato approved these changes

2024-08-13 09:47 UTC, merged