Progettazione dettaglio front-end + fix progettazione logica
Argo-swe/Docs pull request #194
Opened 2024-08-13 14:59 UTC by Rikicavaz77

2024-08-13 18:42 UTC, Rikicavaz77 commented
In un'altra PR:

- Menzionare il salvataggio in `localStorage` e `sessionStorage`;
- Aggiornare la struttura delle cartelle del front-end.

2024-08-16 15:32 UTC, mzecchinato requested changes

2024-08-16 15:32 UTC, mzecchinato commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Frontend/componenti.tex
> +  \item View-Model: crea un binding bidirezionale tra i campi di input e le rispettive variabili;
```suggestion
  \item V-Model: crea un binding bidirezionale tra i campi di input e le rispettive variabili;
```

2024-08-16 16:03 UTC, mzecchinato approved these changes

2024-08-17 06:35 UTC, merged