Sezione Workflow Manuale utente
Argo-swe/Docs pull request #198
Opened 2024-08-17 15:48 UTC by LewentalDigital

[ARGO-287]

2024-08-18 23:29 UTC, LewentalDigital commented
Ho messo le immagini in una grid
Se pensate che sono poco leggibili, le posso mettere piu' grandi e tagliate, magari ad ogni punto, al posto che nella grid alla fine

2024-08-19 07:13 UTC, Rikicavaz77 requested changes
Ho proposto delle piccole modifiche. La grid ci sta parecchio secondo me. Proporrei due modifiche (già suggerite):

- Ho aggiunto i bordi laterali alla figura, per restituire maggiormente l'idea che tutto il workflow sia un flusso unico;
- Ho centrato l'immagine 5 rispetto alla 6, dato che hanno altezze diverse.

2024-08-19 07:13 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_utente.tex
> +\end{enumerate}
```suggestion
\end{enumerate}

\vspace{0.5\baselineskip}
\par Di seguito è riportata una figura che illustra nel dettaglio il flusso da seguire per ottenere una query SQL da utilizzare per interrogare database reali.

```

2024-08-19 07:13 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_utente.tex
> +\end{figure}
```suggestion
\begin{figure}[H]
  \fbox{
  \begin{tabular}{cc}
    \includegraphics[width=65mm]{assets/workflow_1.png} &   \includegraphics[width=65mm]{assets/workflow_2.png} \\
    1 & 2 \\[6pt]
     \includegraphics[width=65mm]{assets/workflow_3.png} &   \includegraphics[width=65mm]{assets/workflow_4.png} \\
    3 & 4 \\[6pt]
    \raisebox{0.3\height}{\includegraphics[width=65mm]{assets/workflow_5.png}} &   \includegraphics[width=65mm]{assets/workflow_6.png} \\
    5 & 6 \\[6pt]
  \end{tabular}}
  \caption{Workflow per ottenere una query SQL}
\end{figure}
```

2024-08-19 10:31 UTC, LewentalDigital commented on sources/documents/3_PB/ManualeUtente/sezione_utente.tex
> +  \item Selezionare il DBMS desiderato;
Aggiungo anche la figura della selezione della lingua
Ma tengo il punto della selezione del DBMS prima, come appare nel menu

2024-08-19 12:00 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_utente.tex
> +  \item Selezionare il DBMS desiderato;
Ok. Selezione lingua possiamo anche ometterla se dà problemi con la grid, tanto è identica alla selezione DBMS.

2024-08-19 12:49 UTC, Rikicavaz77 approved these changes
LGTM

2024-08-19 13:16 UTC, mzecchinato approved these changes
LGTM

2024-08-19 13:52 UTC, merged