Avanzamento progettazione di dettaglio [Specifica Tecnica]
Argo-swe/Docs pull request #204
Opened 2024-08-22 07:59 UTC by Rikicavaz77

[ARGO-310]

[ARGO-310]: https://argo-swe-2.atlassian.net/browse/ARGO-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ARGO-316]

[ARGO-316]: https://argo-swe-2.atlassian.net/browse/ARGO-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-22 16:28 UTC, RaulPianon commented
Ho fatto una prova, ma secondo me viene troppo piccolo. Nel modo in cui era messa prima sforava i bordi e veniva inquadrato solo il primo quadrante. Servirebbe o metterlo su una pagina a sé o almeno far sì che prenda o più margine orizzontale o che stia su più pagine

2024-08-22 16:29 UTC, RaulPianon commented
Potrei anche provare a ridurlo ad un A3 e farlo venire su più pagine

2024-08-23 07:25 UTC, Rikicavaz77 commented
> Reference in new

In qualche modo dovremmo riuscire a renderlo full page.

2024-08-24 12:41 UTC, RaulPianon commented
Non so perché le sotto-sezioni vadano a pagina nuova. Ho messo una sezione introduttiva per indicare cosa viene messo nelle sezioni e le ho divise come avviene nel diagramma:
- Servizi
- Incoming
- Outcoming
Se va bene stasera cerco di iniziare con qualche classe

2024-08-24 12:47 UTC, Rikicavaz77 commented
> Non so perché le sotto-sezioni vadano a pagina nuova. Ho messo una sezione introduttiva per indicare cosa viene messo nelle sezioni e le ho divise come avviene nel diagramma:
> 
> * Servizi
> * Incoming
> * Outcoming
>   Se va bene stasera cerco di iniziare con qualche classe

Se sono sotto-sezioni vuote fa così di solito.

2024-08-27 07:44 UTC, martinaamico approved these changes

2024-08-27 07:44 UTC, martinaamico commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/Classi/incoming.tex
> +        \item \texttt{dictionary\_schema\_file\_path: string} il percorso del file contenente lo schema dei dizionari dati.
```suggestion
        \item \texttt{dictionary\_schema\_file\_path: string} il percorso del file contenente lo schema dei \glossario{dizionario dati}.
```

2024-08-27 07:44 UTC, martinaamico commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/Classi/servizi.tex
> +        \item \texttt{authentication\_repository: AuthenticationRepository}: la repository usata per il recupero dei dati.
```suggestion
        \item \texttt{authentication\_repository: AuthenticationRepository}: la \glossario{repository} usata per il recupero dei dati.
```

2024-08-27 07:44 UTC, martinaamico commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/Classi/servizi.tex
> +        \item \texttt{dictionary\_service: DictionaryService}: il servizio per la gestione dei dizionari dati;
```suggestion
        \item \texttt{dictionary\_service: DictionaryService}: il servizio per la gestione dei \glossario{dizionario dati};
```

2024-08-27 07:44 UTC, martinaamico commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/Classi/servizi.tex
> +        \item \texttt{+ generate\_prompt\_with\_debug(dictionary\_id: integer, query: string, dbms: string, language: string): PromptResponseDto}: genera un prompt con le informazioni di debug;
```suggestion
        \item \texttt{+ generate\_prompt\_with\_debug(dictionary\_id: integer, query: string, dbms: string, language: string): PromptResponseDto}: genera un prompt con le informazioni di \glossario{debug};
```

2024-08-29 20:51 UTC, mzecchinato commented
il documento è impostato giusto, aspetterei le ultime fasi per ricontrollare in modo da essere sicuri di non toccare più il codice, farei semplicemente alcune modifiche alla struttura dei paragrafi:
- `servizi` lo chiamerei `service` (gli altri sono in inglese e anche nella repo è così)
- raggrupperei `port` e `adapter` e per ognuno sottosezioni `incoming` e `outcoming` (come nella repo)
- Diagrammi delle classi` ora è sotto `outcoming - Adapters`

2024-09-01 19:20 UTC, RaulPianon commented
- Sistemati i diagrammi delle singole classi
- Aggiunte le immagini delle singole classi
- Sistemati i paragrafi delle classi
- Modificate le sezioni in modo che siano più affini al codice
- Modificato il diagramma delle classi

2024-09-01 19:22 UTC, RaulPianon commented
Le uniche classi che non vengono descritte sono Dictionaries, Utils e Configuration. Configuration non compare neanche nel diagramma perché non trovo più la dipendenza. Se volete che li aggiunga, ditemelo. Per il resto ho solo un dubbio su una classe che ho già chiesto a Mattia. Utils l'ho aggiunta in "incoming" perché non rientra in nessuna delle divisioni e l'ho sistemata vicino alla classe che ne richiedeva la dipendenza

2024-09-02 07:33 UTC, Rikicavaz77 commented
> Le uniche classi che non vengono descritte sono Dictionaries, Utils e Configuration. Configuration non compare neanche nel diagramma perché non trovo più la dipendenza. Se volete che li aggiunga, ditemelo. Per il resto ho solo un dubbio su una classe che ho già chiesto a Mattia. Utils l'ho aggiunta in "incoming" perché non rientra in nessuna delle divisioni e l'ho sistemata vicino alla classe che ne richiedeva la dipendenza

Utils quasi quasi si potrebbe anche omettere dal diagramma. Poi vediamo.

2024-09-04 14:09 UTC, RaulPianon commented
C'è da sistemare la descrizione di alcuni DTO perché ho un'idea generale di ciò che fanno e non vorrei scrivere cavolate. In più la formattazione delle immagini è errata perché le mette tutte prima del rispettivo paragrafo. Ho provato a sistemare un po', ma non so più che pesci pigliare

2024-09-12 07:53 UTC, mzecchinato requested changes

2024-09-12 07:53 UTC, mzecchinato commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/Pattern/design_pattern.tex
> +        \item \texttt{SqlAlchemyDbManagerFactory}: utilizzata per astrarre la creazione dei diversi tipi di database manager;
```suggestion
        \item \texttt{DbManagerFactory}: utilizzata per astrarre la creazione dei diversi tipi di database manager;
```

2024-09-12 07:53 UTC, mzecchinato commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/Pattern/design_pattern.tex
> +        \item \texttt{TxtaiEmbeddingsManagerFactory}: gestisce la creazione degli embeddings manager, con supporto per diversi algoritmi di embeddings.
```suggestion
        \item \texttt{EmbeddingsManagerFactory}: gestisce la creazione degli embeddings manager, con supporto per diversi algoritmi di embeddings.
```

2024-09-13 18:47 UTC, mzecchinato reviewed
mi sembra ok

2024-09-13 18:47 UTC, mzecchinato commented on sources/documents/3_PB/SpecificaTecnica/ProgettazioneDettaglio/Backend/Pattern/design_pattern.tex
> +        \item TxtaiSearchAlgorithmAdapter;
non dovrebbe essere port?
```suggestion
        \item SearchAlgorithmPort;
```

2024-09-14 09:41 UTC, mzecchinato approved these changes

2024-09-14 09:42 UTC, merged