Debugger manuale utente
Argo-swe/Docs pull request #210
Opened 2024-08-27 15:05 UTC by martinaamico

2024-08-28 13:44 UTC, Rikicavaz77 requested changes

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +Per il tecnico è disponibile uno strumento di controllo per i meccanismi di generazione del \glossario{prompt} che può aiutare a comprendere ed analizzare i passaggi algoritmici che hanno prodotto il
```suggestion
\par Per il Tecnico è disponibile uno strumento di controllo per i meccanismi di generazione del \glossario{prompt} che aiuta a comprendere e analizzare i passaggi algoritmici che hanno prodotto il prompt restituito sulla base di una interrogazione. Il \glossario{debug} assiste il Tecnico nella fase di miglioramento del \glossario{dizionario dati}, poiché fornisce una panoramica dell'interazione tra i modelli di intelligenza artificiale e il dizionario stesso. L'obiettivo di questa funzionalità è individuare le aree del dizionario dati che necessitano di aggiornamenti, con particolare attenzione alle descrizioni in linguaggio naturale di tabelle e colonne.
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +Per utilizzare questa funzionalità il tecnico deve scrivere una richiesta nella chat apposita (sezione utente 6.1) e una volta ottenuto il prompt è necessario cliccare l'icona del punto interrogativo
```suggestion

\par Per utilizzare questa funzionalità, il Tecnico deve inserire un messaggio nell'apposita maschera di richiesta all'interno della chat (sezione utente 6.1). Una volta ottenuto il prompt, è necessario cliccare l'icona del punto interrogativo in alto a destra, da cui si aprirà un'altra finestra sovrapposta a quella attuale.
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +Per utilizzare questa funzionalità il tecnico deve scrivere una richiesta nella chat apposita (sezione utente 6.1) e una volta ottenuto il prompt è necessario cliccare l'icona del punto interrogativo
sezione utente 6.1. Qui possiamo mettere il link diretto alla sezione.

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +  \includegraphics[width=1\textwidth]{assets/tasto_info_debug.png}
```suggestion
  \includegraphics[width=\textwidth]{assets/tasto_info_debug.png}
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +Nel messaggio prodotto è documentato il modo in cui le descrizioni interagiscono con il modello di \glossario{AI}. In ordine verranno visualizzate le seguenti informazioni:
```suggestion
\par Nel messaggio di debug è documentato il modo in cui le descrizioni interagiscono con il modello di \glossario{AI}. In ordine verranno visualizzate le seguenti informazioni: 
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +  \item Analisi della prima fase della generazione del prompt con una lista delle tabelle considerate rilevanti dal modello di cui si riportano le seguenti informazioni:
```suggestion
  \item Analisi della prima fase della generazione del prompt con una lista delle tabelle considerate rilevanti dal modello, di cui si riportano le seguenti informazioni:
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +  \item Analisi della seconda fase di generazione dei prompt con la lista delle tabelle pertinenti di cui viene riporto il motivo per cui una tabella viene inserita o meno nel prompt.
```suggestion
  \item Analisi della seconda fase di generazione del prompt con una lista delle tabelle pertinenti, di cui viene indicato il motivo per cui sono state inserite o meno nel prompt finale.
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +
```suggestion
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +  \includegraphics[width=1\textwidth]{assets/analisi_debug1.jpg}
```suggestion
  \includegraphics[width=\textwidth]{assets/analisi_debug1.jpg}
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +  \includegraphics[width=1\textwidth]{assets/analisi_debug2.jpg}
```suggestion
  \includegraphics[width=\textwidth]{assets/analisi_debug2.jpg}
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +Per chiudere il messaggio generato è necessario cliccare la x in alto a destra e sarà possibile tronare alla chat con il prompt generato.
```suggestion
\par Cliccando il pulsante di chiusura in alto a destra, il modale di debug verrà nascosto e sarà possibile visualizzare nuovamente il prompt generato.
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +  \includegraphics[width=1\textwidth]{assets/tasto_close_debug.png}
```suggestion
  \includegraphics[width=\textwidth]{assets/tasto_close_debug.png}
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +E' possibile scaricare il messaggio generato cliccando il simbolo di download rosso in alto a destra in modo da conservarlo in locale e utilizzarlo per migliorare il \glossario{dizionario dati} o per
```suggestion
Il messaggio di debug può essere scaricato in formato \textit{txt}, in modo da conservarlo in locale e utilizzarlo per migliorare il \glossario{dizionario dati} o per produrre analisi a posteriori.
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +  \includegraphics[width=1\textwidth]{assets/tasto_dawnload_debug.png}
```suggestion
  \includegraphics[width=\textwidth]{assets/tasto_dawnload_debug.png}
```

2024-08-28 13:44 UTC, Rikicavaz77 commented on sources/documents/3_PB/ManualeUtente/sezione_tecnico.tex
> +  \caption{Tasto download del messaggio di debug}
```suggestion
  \caption{Download del messaggio di debug}
```

2024-08-30 06:51 UTC, Rikicavaz77 commented
Un'altra cosa. Il pulsante di download è di colore blu, non più rosso.

2024-09-03 16:09 UTC, CristoMarco approved these changes
Tutto a posto

2024-09-03 16:13 UTC, Rikicavaz77 approved these changes
LGTM

2024-09-03 16:14 UTC, merged