Verbale Interno 2024-04-25
Argo-swe/Docs pull request #56
Opened 2024-04-27 13:21 UTC by RaulPianon

2024-04-27 16:09 UTC, RaulPianon commented
[VerbaleInterno_2024-04-25.pdf](https://github.com/Argo-swe/Docs/files/15138703/VerbaleInterno_2024-04-25.pdf)

2024-04-27 21:37 UTC, mzecchinato requested changes
- le date all'interno del testo, negli altri documenti, mi sembrava fossero per esteso e solo nelle tabelle nel formato `YYYY-MM-DD`
- dizionario dati in altri verbali era senza le maiuscole, come testo normale anche se riferito al glossario
- NOTA da discutere: non so se il discorso maiuscole vogliamo portarlo anche a termini come "Diario di Bordo"

riguardo i problemi di spaziatura dopo i comandi che non hanno parametri, va aggiunto un backslash dopo il comando per esempio `\Glossario\`, mentre per cose tipo `\glossario{termine}` non serve

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Vengono spiegate le attività svolte come la stesura della struttura del \Glossario, [mancano parti che ha fatto Tommaso]. Viene inoltre puntualizzata la necessità di un incontro con il Professor
```suggestion
\par Vengono spiegate le attività svolte come la stesura della struttura del \Glossario, [mancano parti che ha fatto Tommaso]. Viene inoltre puntualizzata la necessità di un incontro con il Professor. Tullio Vardanega per un chiarimento sullo stabilimento di un criterio col quale inserire i termini nel \Glossario. Del \Glossario\ si discute anche il tipo di uso (se esterno o interno) e il numero di occorrenze di termini che nei documenti vanno indicati come presenti nel documento. Questi dubbi verranno esposti al Diario di Bordo del 26 aprile 2024.
```
da controllare la spaziatura dopo il comando `\Glossario`

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Viene esposta la strutturazione del \glossario{Dizionario Dati} in formato \glossario{JSON} che è stato poi utilizzato come test dal \Progettista in fase di apprendimento delle tecnologie. È sta
```suggestion
\par Viene esposta la strutturazione del \glossario{dizionario dati} in formato \glossario{JSON} che è stato poi utilizzato come test dal \Progettista\ in fase di apprendimento delle tecnologie. È stata inoltre studiata la possibile composizione del \glossario{prompt} finale che sarà disponibile all'utente.
```
stesso problema di spaziatura dopo l'uso del comando `\Progettista`

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Vengono spiegate le tecnologie studiate e i test svolti su un \glossario{Dizionario Dati} di prova per comprendere il funzionamento dei modelli. Vengono inoltre esposti i dubbi e le difficoltà r
```suggestion
\par Vengono spiegate le tecnologie studiate e i test svolti su un \glossario{dizionario dati} di prova per comprendere il funzionamento dei modelli. Vengono inoltre esposti i dubbi e le difficoltà riscontrati, con un confronto tra gli altri membri per organizzare incontri e sistemare i problemi sorti.
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item Sono state riscontrate delle difficoltà iniziali nel lavorare ad un motore di database con esempi di database [SCLight], altrimenti non c'era modo di testare con [txtai].
```suggestion
	\item Sono state riscontrate delle difficoltà iniziali nel lavorare ad un motore di database con esempi di database [SQLite], altrimenti non c'era modo di testare con [txtai].
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item L'idea iniziale è stata quella di prendere un database in formato \glossario{JSON} che potesse essere analizzato assieme alla \glossario{query} dell'utente e restituire il \glossario{prompt} c
```suggestion
	\item L'idea iniziale è stata quella di prendere uno schema database in formato \glossario{JSON} che potesse essere analizzato assieme alla \glossario{query} dell'utente e restituire il \glossario{prompt} con le parole prese dal \glossario{dizionario dati} e un punteggio in base all'accuratezza.
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item Viene anche esposta la necessità di trovare un formato migliore per la \glossario{LLM} che verrà poi scelta, in modo che il linguaggio risulti meno tecnico per la \glossario{LLM} o trovare un
```suggestion
	\item Viene anche esposta la necessità di trovare un formato migliore per la \glossario{LLM} che verrà poi scelta, in modo che il linguaggio risulti meno tecnico per la \glossario{LLM} o trovare un modello che supporti la lettura del \glossario{dizionario dati} nel formato richiesto.
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Vengono spiegate le attività svolte come la stesura della struttura del \Glossario, [mancano parti che ha fatto Tommaso]. Viene inoltre puntualizzata la necessità di un incontro con il Professor
```suggestion
\par Vengono spiegate le attività svolte come la stesura della struttura del \Glossario, [mancano parti che ha fatto Tommaso]. Viene inoltre puntualizzata la necessità di un incontro con il Professor. Tullio Vardanega per un chiarimento sullo stabilimento di un criterio col quale inserire i termini nel \Glossario. Relativamente al \Glossario\ si discute anche se il documento sia a uso interno o esterno, e il numero di occorrenze di termini che nei documenti vanno indicati come riferimento al \Glossario. Questi dubbi verranno esposti al Diario di Bordo del 26 aprile 2024.
```
da controllare la spaziatura dopo il comando `\Glossario` in nel caso di utilizzo all'interno della frase forse manca

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Vengono esposte al gruppo le funzionalità di \glossario{Jira}: in particolare la strutturazione del diagramma di Gannt per avere una vista grafica sullo sprint e sulle attività a questo legate.
```suggestion
\par Vengono esposte al gruppo le funzionalità di \glossario{Jira}: in particolare la strutturazione del \glossario{diagramma di Gannt} per avere una vista grafica sullo stato di pianificazione dello sprint e sulle attività a questo legate. Vengono inoltre spiegati i ticket e l'interazione tra questi e le pull request di Github, le quali si potranno aprire collegando un ticket e chiudere con la conseguente chiusura di questi.
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Vengono discussi i punti salienti da trattare nel prossimo Diario di Bordo del 2024-04-26:
```suggestion
\par Vengono discussi i punti salienti da trattare nel prossimo Diario di Bordo del 26 aprile 2024:
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item Studio preliminare delle tecnologie \ \rightarrow\ Studio di [Txtai], modelli e interazione tra questi e il \glossario{Dizionario Dati} in forma \glossario{JSON}.
```suggestion
	\item Studio preliminare delle tecnologie \ \rightarrow\ Studio di [Txtai], modelli e interazione tra questi e il \glossario{dizionario dati} in formato \glossario{JSON}.
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item Stesura del \glossario{Dizionario Dati}
```suggestion
	\item Stesura del \glossario{dizionario dati}
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item Modifica del template \glossario{LaTeX} \ \rightarrow\ Modifiche estetiche e funzionali, come il cambiamento della tabella delle attività da svolgere con l'inserimento delle colonne per \gloss
```suggestion
	\item Modifica del template \glossario{LaTeX} \ \rightarrow\ Modifiche estetiche e funzionali, come il cambiamento della tabella delle attività da svolgere con l'inserimento delle colonne per \glossario{ticket} e date di scadenza associate
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Le seguenti sezioni sono state poi inserite all'interno del documento per la presentazione al Diario di Bordo del 2024-04-26.
```suggestion
\par Le seguenti sezioni sono state poi inserite all'interno del documento per la presentazione al Diario di Bordo del 26 aprile 2024.
```

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item Inserimento nel \Glossario dei termini individuati durante la stesura dei documenti di progetto \ \rightarrow\ Il \Glossario è dotato di una struttura completa, ma deve essere popolato con i t
```suggestion
	\item Inserimento nel \Glossario\ dei termini individuati durante la stesura dei documenti di progetto \ \rightarrow\ Il \Glossario\ è dotato di una struttura completa, ma deve essere popolato con i termini individuati finora nei documenti.	
```
da controllare la spaziatura dopo il comando `\Glossario`

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item \Glossario come documento interno o esterno \ \rightarrow\ Ossia se i termini da inserire sono a discrezione del gruppo o se devono essere aggiunti anche termini sconosciuti all'esterno [rived
```suggestion
	\item \Glossario\ come documento interno o esterno \ \rightarrow\ Ossia se i termini da inserire sono a discrezione del gruppo o se devono essere aggiunti anche termini sconosciuti all'esterno [rivedere]
```
da controllare la spaziatura dopo il comando `\Glossario`

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item Numero di occorrenze di un termine del \Glossario da formattare \ \rightarrow\ Ossia se nei documenti ogni termine indicato nel \Glossario deve essere segnalato o se bastano le prime istanze d
```suggestion
	\item Numero di occorrenze di un termine del \Glossario\ da formattare \ \rightarrow\ Ossia se nei documenti ogni termine indicato nel \Glossario\ deve essere segnalato o se bastano le prime istanze di questo.
```
da controllare la spaziatura dopo il comando `\Glossario`

2024-04-27 21:37 UTC, mzecchinato commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par La discussione si è centrata sulla continuazione del documento \AnalisiDeiRequisiti e sulla prossima trascrizione del documento in formato \glossario{LateX}.
```suggestion
\par La discussione si è centrata sulla continuazione del documento \AnalisiDeiRequisiti\ e sulla prossima trascrizione del documento in formato \glossario{LateX}.
```
problema di spaziatura dopo `\AnalisiDeiRequisiti\`

2024-04-28 06:16 UTC, Rikicavaz77 commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +	\item Sono state riscontrate delle difficoltà iniziali nel lavorare ad un motore di database con esempi di database [SCLight], altrimenti non c'era modo di testare con [txtai].
Toglierei le parentesi quadre

2024-04-28 06:18 UTC, Rikicavaz77 commented
> NOTA da discutere: non so se il discorso maiuscole vogliamo portarlo anche a termini come "Diario di Bordo"

Secondo me diario di bordo possiamo lasciarlo così com'è, cioè tutto minuscolo

2024-04-28 06:18 UTC, Rikicavaz77 commented
> le date all'interno del testo, negli altri documenti, mi sembrava fossero per esteso e solo nelle tabelle nel formato YYYY-MM-DD

Si le metterei per esteso, altrimenti ne risente la leggibilità

2024-04-28 09:26 UTC, mzecchinato commented
> > NOTA da discutere: non so se il discorso maiuscole vogliamo portarlo anche a termini come "Diario di Bordo"
> 
> Secondo me diario di bordo possiamo lasciarlo così com'è, cioè tutto minuscolo

Al momento è con le maiuscole

2024-04-28 09:29 UTC, Rikicavaz77 commented
> Al momento è con le maiuscole

Allora è da cambiare secondo me

2024-04-29 09:41 UTC, Rikicavaz77 commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Vengono spiegate le attività svolte come la stesura della struttura del \Glossario, [mancano parti che ha fatto Tommaso]. Viene inoltre puntualizzata la necessità di un incontro con il Professor
Meglio usare \Gls al posto di \Glossario

2024-04-29 09:42 UTC, Rikicavaz77 commented on sources/documents/RTB/Verbali/Interni/VerbaleInterno_2024-04-25/capitolo-riunione.tex
> +\par Viene esposta la strutturazione del \glossario{Dizionario Dati} in formato \glossario{JSON} che è stato poi utilizzato come test dal \Progettista in fase di apprendimento delle tecnologie. È sta
Il comando Progettista non ha molto senso a mio parere

2024-04-30 12:36 UTC, mzecchinato approved these changes

2024-04-30 16:31 UTC, merged