Porting Analisi dei Requisiti e modifiche generali
Argo-swe/Docs pull request #57
Opened 2024-04-28 14:45 UTC by stoccotommaso02

[ARGO-16]
La versione in LaTeX dell'Analisi dei Requisiti comprende i casi d'uso sviluppati finora con delle modifiche non sostanziali rispetto alla versione di bozza precedente.
Le differenze principali sono:
- TODO inserito in porzioni di documento incomplete o da espandere
- Immagini assenti poiché una versione finale dei casi d'uso non è ancora realizzabile, perciò nomi/numeri/relazioni potrebbero ancora variare
- La maggior parte dei riferimenti generici ad utente (inteso come persona) sono stati sostituiti con l'Attore che il caso d'uso descrive

2024-04-29 15:36 UTC, mzecchinato requested changes
ci sono vari "dizionario dati" senza il comando `\glossario{dizionario dati}` andrebbe aggiunto, ne ho segnati alcuni, ma conviene fare un replace

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/registro_modifiche.tex
> +		\hline 0.0.3 & 2024-04-18 & \marco, \martina, \sebastiano, \mattia & \raul & Ulteriore aprofondimento casi d'uso \\
```suggestion
		\hline 0.0.3 & 2024-04-18 & \marco, \martina, \sebastiano, \mattia & \raul & Ulteriore approfondimento casi d'uso \\
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/registro_modifiche.tex
> +		\hline 0.0.2 & 2024-04-15 & \marco, \martina, \sebastiano & \raul & Aggiunti \ref{UC3}, \ref{UC4}, \ref{UC5}, \ref{UC1}, \ref{UC10} \\
aggiungere riferimento UC3

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/descrizione.tex
> +  \item Selezione del dizionario dati da interrogare;
```suggestion
  \item Selezione del \glossario{dizionario dati} da interrogare;
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/descrizione.tex
> +  \item Esecuzione di una batteria di test predefinita nella configurazione del dizionario dati.
```suggestion
  \item Esecuzione di una batteria di test predefinita nella configurazione del \glossario{dizionario dati}.
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/descrizione.tex
> +Da quanto emerso dall’analisi del capitolato da parte della Proponente, è stato evidenziato un interesse nello sviluppo di questo progetto per varie tipologie di utenti.\\
```suggestion
Dopo una discussione e analisi con la Proponente, è stato evidenziato un interesse nello sviluppo di questo progetto per varie tipologie di utenti.\\
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +L’Utente desidera inserire una richiesta in qualsiasi linguaggio naturale al fine di ottenere, in seguito, il prompt che selezioni la parte del dizionario dati più inerente alla richiesta.
```suggestion
L’Utente desidera inserire una richiesta in qualsiasi linguaggio naturale al fine di ottenere il prompt che selezioni la parte del dizionario dati più inerente alla richiesta.
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +  \item L’Utente scrive una interrogazione nell’ apposito box su cui poi il sistema potrà produrre un prompt in seguito.
```suggestion
  \item L’Utente scrive un'interrogazione nell’apposito box su cui poi il sistema potrà produrre un prompt in seguito.
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +  \item Se non è stata selezionata una diversa lingua per l’inserimento quella di default è l’italiano, se è stata selezionata è quella su cui si baserà la traduzione.
```suggestion
  \item L'Utente seleziona la lingua di inserimento, se non selezionata viene utilizzato l'italiano di default.
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +  \item Nella applicazione web è stato caricato precedentemente almeno un dizionario dati.
```suggestion
  \item Nella applicazione web è stato caricato precedentemente almeno un \glossario{dizionario dati}.
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +  \item Un dizionario dati è stato selezionato in modo corretto ed univoco;
```suggestion
  \item Un \glossario{dizionario dati} è stato selezionato in modo corretto ed univoco;
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +L’Utente desidera ottenere un prompt al fine di utilizzarlo poi con LLM esterni per generare \glossario{query} sql fornendo parti ristrette di dizionario dati.
```suggestion
L’Utente desidera ottenere un prompt al fine di utilizzarlo poi con LLM esterni per generare \glossario{query} sql fornendo parti ristrette di \glossario{dizionario dati}.
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +  \item L’Utente inserisce una interrogazione in linguaggio naturale nel box testuale apposito;
```suggestion
  \item L’Utente inserisce un'interrogazione in linguaggio naturale nel box testuale apposito;
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +  \item L’Utente seleziona una lingua da una lista predefinita di lingue.La scelta è tra:
```suggestion
  \item L’Utente seleziona una lingua da una lista predefinita di lingue. La scelta è tra:
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +L’Utente vuole selezionare il prompt che è stato generato dal sistema per poter usarlo all’interno della richiesta ad un LLM esterno al fine di generare una query.
```suggestion
L’Utente vuole selezionare il prompt che è stato generato dal sistema per poterlo usare all’interno della richiesta ad un LLM esterno al fine di generare una query.
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +\paragraph*{Descrizione} Il sistema mostra un messaggio d’errore relativo al mancato caricamento del nuovo dizionario dati che si desidera inserire nel momento in cui vengono rilevate anomalie relati
```suggestion
TODO immagine\paragraph*{Descrizione} Il sistema mostra un messaggio d’errore relativo al mancato caricamento del nuovo dizionario dati che si desidera inserire nel momento in cui vengono rilevate anomalie relative al suo inserimento.
```

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +\paragraph*{Estensione}
manca TODO o va rimossa?

2024-04-29 15:36 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +\paragraph*{Descrizione} Il Tecnico vuole modificare un dizionario dato già presente nel sistema.
```suggestion
\paragraph*{Descrizione} Il Tecnico vuole modificare un \glossario{dizionario dati} già presente nel sistema.
```

2024-04-30 09:02 UTC, stoccotommaso02 commented
@mzecchinato Per qualche mio problema con branch la versione dei casi d'uso caricata era tagliata, lo UC1 aveva il contenuto del 3 e tutto il testo di UC1 e 2 era mancante. Col nuovo push dovrebbe essere stato corretto questo oltre alle altre modifiche chieste in review

2024-04-30 17:54 UTC, martinaamico requested changes
Da correggere

2024-04-30 17:54 UTC, martinaamico commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +L’errore relativo all’ incompletezza delle credenziali viene mostrato a seguito del rilevamento parziale delle credenziali inserite da parte dell’Utente Non Autenticato.
```suggestion
L’errore relativo all’incompletezza delle credenziali viene mostrato a seguito del rilevamento parziale delle credenziali inserite da parte dell’Utente Non Autenticato.
```

2024-04-30 17:54 UTC, martinaamico commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +L’Utente desidera selezionare il \glossario{\glossario{dizionario dati}} sul quale basare in seguito l’interrogazione in linguaggio naturale.
```suggestion
L’Utente desidera selezionare il \glossario{dizionario dati} sul quale basare in seguito l’interrogazione in linguaggio naturale.
```

2024-04-30 21:29 UTC, Rikicavaz77 commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +L’Utente desidera inserire una richiesta in qualsiasi linguaggio naturale al fine di ottenere, in seguito, il prompt che selezioni la parte del dizionario dati più inerente alla richiesta.
da risolvere

2024-04-30 21:34 UTC, Rikicavaz77 commented
Da risolvere https://github.com/Argo-swe/Docs/pull/57#discussion_r1583262331

2024-05-02 07:44 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +L’Utente desidera inserire una richiesta in qualsiasi linguaggio naturale al fine di ottenere, in seguito, il prompt che selezioni la parte del dizionario dati più inerente alla richiesta.
mi risulta ancora presente, ma spostato nella descrizione di UC3, la risolvo qui e la aggiungo nuova

2024-05-02 07:46 UTC, mzecchinato requested changes
modifica dopo aggiunta conenuti UC1 e UC2

2024-05-02 07:46 UTC, mzecchinato commented on sources/documents/RTB/AnalisiDeiRequisiti/casiduso.tex
> +L’Utente desidera inserire una richiesta in qualsiasi linguaggio naturale al fine di ottenere, in seguito, il prompt che selezioni la parte del \glossario{dizionario dati} più inerente alla richiesta
```suggestion
L’Utente desidera inserire una richiesta in qualsiasi linguaggio naturale al fine di ottenere il prompt che selezioni la parte del \glossario{dizionario dati} più inerente alla richiesta. 
```

2024-05-02 07:48 UTC, mzecchinato commented
> Da risolvere [#57 (comment)](https://github.com/Argo-swe/Docs/pull/57#discussion_r1583262331)

mi risulta ancora presente dopo l'aggiunta dei contenuti UC1 e UC2, l'ho segnata risolta e aggiunta di nuovo nel posto corretto

2024-05-03 13:35 UTC, stoccotommaso02 commented
La struttura dei casi d'uso è stata frammentata in file multipli, facilitando la review, la redazione e l'aggiunta di elementi. Inoltre è stata omologata la formattazione.
Logicamente e contenutisticamente ho effettuato una sola variazione: il precedente UC "Visualizzazione singolo dizionario dati" era sottocaso di due casi d'uso diversi ("Visualizzazione lista dizionari dati" e "Visualizzazione dati dizionario"). Ciò non è possibile, per cui l'ho reso un caso d'uso autonomo incluso dai due sopra menzionati (questo ha cambiato leggermente i riferimenti numerici ad alcuni casi d'uso)

2024-05-06 13:13 UTC, martinaamico reviewed
Nel documento scaricato la versione in basso a sinistra mi risulta essere 0.0.1 e non 0.0.4

2024-05-06 14:31 UTC, stoccotommaso02 commented
> Nel documento scaricato la versione in basso a sinistra mi risulta essere 0.0.1 e non 0.0.4

Ho sistemato

2024-05-07 08:26 UTC, martinaamico approved these changes
ok

2024-05-07 08:31 UTC, mzecchinato approved these changes

2024-05-07 08:31 UTC, merged