Caricato template per build documenti in Latex
Argo-swe/Docs pull request #7
Opened 2024-03-17 10:16 UTC by mzecchinato

2024-03-18 13:50 UTC, stoccotommaso02 commented
Ho convertito la PR in draft, va riordinato un po' il contenuto aggiunto e fatte lievi modifiche. Me ne occupo io

2024-03-18 14:28 UTC, stoccotommaso02 commented
@Rikicavaz77 ti ho aggiunto alla review per un controllo sul'ordinamento

2024-03-18 16:16 UTC, Rikicavaz77 requested changes
- [ ] Farei una cartella `CANDIDATURA` in cui inserire le subdirectory Verbale 1, Verbale 2, ecc.

- [ ] _Proposta: Magari, all'interno delle cartelle dei rispettivi documenti, si potrebbe creare la subdirectory `assets` per inserire immagini specifiche._

- [x] Inoltre, io e @RaulPianon abbiamo lavorato con il font `Poppins`, sarebbe interessante introdurlo anche qui.

- [ ] Infine, è da valutare se inserire, magari in copertina, il logo di `Unipd`.

2024-03-18 16:18 UTC, Rikicavaz77 commented
@mzecchinato più tardi ci sarebbe da fare un rapido check delle modifiche.

2024-03-18 16:26 UTC, Rikicavaz77 requested changes

2024-03-18 16:26 UTC, Rikicavaz77 commented on tools/README_BUILD.md
> +    -   **Norme di Progetto**
Ci sono riferimenti a documenti post-candidatura.

2024-03-18 16:26 UTC, Rikicavaz77 commented on tools/.dockerignore
> +.gitignore
Mi pare vadano cambiati i `path`.

2024-03-19 14:37 UTC, Rikicavaz77 commented
@stoccotommaso02 nella copertina la versione finale è 1.0, mentre nella tabella è 0.1

2024-03-21 21:47 UTC, stoccotommaso02 commented
Il template è stato modificato, adattandolo alle necessità e proposte del gruppo.
I cambi principali sono:
- Nuova struttura dei documenti
- Rimossi riferimenti ad elementi non presenti nello stato attuale del progetto
- Sistema di script di compilazione nuovo: più semplice e adatto alla struttura del progetto
- Aggiornato l'immagine Docker: Ora utilizza Ubuntu 22.04 e package più aggiornati.

Sono inoltre inclusi i sorgenti dei verbali esterni e dei primi due verbali interni

2024-03-21 23:27 UTC, Rikicavaz77 requested changes
Potresti allegarmi in un commento i pdf generati dai template LaTeX dei due verbali interni? 

Così li revisiono rapidamente prima di integrare i sorgenti nel ramo base.

2024-03-21 23:27 UTC, Rikicavaz77 commented on sources/model/modelassets/signatures/.gitkeep
Questo file può essere rimosso.

2024-03-21 23:27 UTC, Rikicavaz77 commented on tools/.dockerignore
> +.gitignore
Dopo il riordinamento, il file .gitignore a cui si faceva riferimento si trova al livello di gerarchia precedente, accessibile con "../".

2024-03-22 09:29 UTC, stoccotommaso02 commented
Ho attuato le modifiche richieste, più qualche correzione ai verbali interni. Qui in allegato i pdf prodotti

[VerbaleInterno_240306.pdf](https://github.com/Argo-swe/Docs/files/14720435/VerbaleInterno_240306.pdf)
[VerbaleInterno_240307.pdf](https://github.com/Argo-swe/Docs/files/14720437/VerbaleInterno_240307.pdf)

2024-03-22 09:39 UTC, Rikicavaz77 requested changes
> [VerbaleInterno_240306.pdf](https://github.com/Argo-swe/Docs/files/14720435/VerbaleInterno_240306.pdf)

> [VerbaleInterno_240307.pdf](https://github.com/Argo-swe/Docs/files/14720437/VerbaleInterno_240307.pdf)

Le correzioni sono corrette. Nel pdf del 6 marzo, sezione 2.2.2., Martina dall’Amico andrebbe con la "D" maiscuola.

Nella colonna versione è corretta l'indentazione verso destra? Nei verbali esterni era a sinistra.

Nella tabella To Do è possibile centrare verticalmente il testo nelle celle come nel registro delle modifiche?

2024-03-22 11:08 UTC, stoccotommaso02 commented
Le modifiche richieste sono state ultiamte, tranne l'allineamento delle versioni nel registro modifiche.

2024-03-22 11:10 UTC, Rikicavaz77 commented
> A mio avviso si può eseguire il merge, aprendo una issue in seguito per eseguire quella modifica

Ok apriamo un issue etichettato come bug per discutere il problema.

2024-03-22 11:14 UTC, Rikicavaz77 commented on sources/model/global.tex
> +\newcommand{\Responsabili}{\textit{Responsabili di Progetto}}
Nella riunione di oggi abbiamo deciso di lasciare i ruoli al singolare, con le rispettive versioni al femminile.

2024-03-22 11:14 UTC, Rikicavaz77 commented on sources/model/global.tex
> +\newcommand{\Amministratrica}{\textit{Amministratrice}}
Il nome del comando è `Amministratrice`

2024-03-22 11:51 UTC, Rikicavaz77 approved these changes
LGTM

2024-03-22 11:51 UTC, merged