Verbale interno del 7 maggio nuovo branch
Argo-swe/Docs pull request #78
Opened 2024-05-13 19:19 UTC by RaulPianon

Seconda versione. Deve ancora essere verificato, ma dovrebbe anche essere già completo

2024-05-14 11:22 UTC, LewentalDigital requested changes

2024-05-14 11:22 UTC, LewentalDigital commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-07/capitolo-riunione.tex
> +\par Il meeting si è concluso con le attività definite che verranno convertite in ticket su \glossario{Jira}: queste si concentreranno sull'avanzamento dei lavori sui documenti quali \AdR, \Gls, \PdP
```suggestion
\par Il meeting si è concluso con le attività definite che verranno convertite in ticket su \glossario{Jira}: queste si concentreranno sull'avanzamento dei lavori sui documenti quali \AdR, \Gls, \PdP, \NdP\ e \PdQ\ e sul proseguimento dello sviluppo del Proof of Concept.
```
Così la e viene separata

2024-05-20 09:47 UTC, Rikicavaz77 commented
[ARGO-39]

2024-05-21 08:54 UTC, LewentalDigital approved these changes
LGTM

2024-05-21 09:06 UTC, merged