Feature pdq sprint 3
Argo-swe/Docs pull request #81
Opened 2024-05-21 13:28 UTC by martinaamico

Inserimento metriche di valutazione con descrizioni e formule e sezione strumenti

2024-05-21 15:34 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_2.tex
Ci sono molti commenti qui, sono stati lasciati perchè possono essere utili in futuro?

2024-05-21 20:22 UTC, Rikicavaz77 commented
è stato caricato anche il pdf del Piano di Progetto, va eliminato.

2024-05-22 16:16 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_14.tex
> +        \item $N_{com}$: Numero di linee di commento;
```suggestion
        \item $L_{com}$: Numero di linee di commento;
```
Perchè nella descrizione è stata usata la L

2024-05-22 16:54 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_3.tex
Cambiare nome file in metriche_M_4_2.tex
Il nome attuale è metriche_M_4_3.tex ma la metrica presente è la M.4.2

2024-05-22 16:59 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/accertamento_introduzione.tex
> +\subsection{processo}
```suggestion
\subsection{Processo}
```

2024-05-22 17:42 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_5.tex
Cambiare nome file in metriche_M_4_4.tex
Il nome attuale è metriche_M_4_5.tex ma la metrica presente è la M.4.4

2024-05-22 17:53 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_17.tex
Specificare che riguarda il tempo di risposta di generazione del prompt

2024-05-22 17:57 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_13.tex
La descrizione e il motivo sono molto vaghi
Approfondire, specificando cosa sia la risposta nel caso del nostro software

2024-05-22 17:58 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M2/M_2_8.tex
La misurazione è inefficacie, trovare una migliore o metter in TODO

2024-05-22 18:06 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/accertamento_introduzione.tex
> +\subsection{Didascalia}
Esiste anche un caso dove nella didascalia è presente "**Interpretazione risultato**"
Indicare che è possibile che appaia nella didascalia (ha senso?)

2024-05-22 18:11 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/accertamento_qualita.tex
> +Le metriche elencate verranno utilizzate e valutate all'interno di un modello SPICE(g) al fine di promuovere un ciclo continuo di valutazione e miglioramento. Alla fine di ogni sprint, dove possibile
```suggestion
Le metriche elencate verranno utilizzate e valutate all'interno di un modello \glossario{SPICE} al fine di promuovere un ciclo continuo di valutazione e miglioramento. Alla fine di ogni sprint, dove possibile in modo automatico o manualmente per alcune metriche, verranno valutate le aree di maggior difficoltà e quelle su cui è necessario migliorare. Successivamente, saranno implementate azioni correttive mirate per affrontare eventuali problemi riscontrati.
```

2024-05-22 18:13 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/strumenti.tex
> +    \item \textbf{Discord} \href{https://discord.com}{(https://discord.com)} (Ultimo accesso: 2024-05-18) - Piattaforma utilizzata per lo svolgimento di riunioni formali ed informali del team, attrav
```suggestion
    \item \textbf{Discord} \href{https://discord.com}{(https://discord.com)} (Ultimo accesso: 2024-05-18) - Piattaforma utilizzata per lo svolgimento di riunioni formali ed informali del team, attraverso la creazione di un server apposito con un canale dedicato ai messaggi di testo e diverse sale virtuali dedicate alle conversazioni vocali.
```

2024-05-22 18:25 UTC, LewentalDigital requested changes
Oltre alle suggestion inserite nei commenti, rimuovere le seguenti metriche considerate inutili o non adeguate:
M.1.5, M.1.6, M.1.16, M.1.19, M.1.21, M.3.1, M.3.2, M.4.3

- [x] assicurarsi di cambiare la notazione delle altre metriche se il loro ordine è infuenzato dall'eliminazione di queste
- [ ] assicurarsi di cambiare il nome del file delle metriche a cui è cambiata la notazione

2024-05-22 18:30 UTC, LewentalDigital commented
Metriche problemtiche:

- M.1.10 da trovare altro metodo
- M.1.11
- M.1.12
- M.1.15 capire se tenere questa a sfavore di M 1 11 e M 1 12
- M.3.3 difficile da applicare
- M.3.4 capire come e se è possibile da implementare

2024-05-28 08:57 UTC, stoccotommaso02 requested changes
Metriche in più sulle NdP rispetto al PdQ:
- modified condition/decision coverage (M.1.2)
- Functional size measurement (M.1.5)
- Accuratezza rispetto alle attese (M.1.6)
- MANCANTE (o reindirizzato?): Impatto delle modifiche (M.1.12 nel PdQ)

2024-05-29 08:44 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_3.tex
> +\subsubsubsection{Vocaboli inseriti nel vocabolario ad ogni sprint}
```suggestion
\subsubsubsection{Vocaboli inseriti nel glossario ad ogni sprint}
```

2024-05-29 08:44 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_3.tex
> +    \item \textbf{Nome}: Vocaboli inseriti nel vocabolario ad ogni sprint;
```suggestion
    \item \textbf{Nome}: Vocaboli inseriti nel glossario ad ogni sprint;
```

2024-05-29 08:44 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_3.tex
> +    \item \textbf{Motivo}: Monitorare il tasso di crescita del vocabolario del progetto aiuta a valutare la complessità e l'evoluzione del linguaggio tecnico utilizzato all'interno del team e può evi
```suggestion
    \item \textbf{Motivo}: Monitorare il tasso di crescita del glossario del progetto aiuta a valutare la complessità e l'evoluzione del linguaggio tecnico utilizzato all'interno del team e può evidenziare la necessità di formazione aggiuntiva o di chiarimenti sui concetti;
```

2024-05-29 08:45 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_3.tex
> +    \item \textbf{Misurazione}: La metrica misura il numero di nuove parole introdotte nel vocabolario secondo la formula:
```suggestion
    \item \textbf{Misurazione}: La metrica misura il numero di nuove parole introdotte nel glossario secondo la formula:
```

2024-05-29 08:45 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M4/M_4_3.tex
> +        \text{Parole inserite nel vocabolario ad ogni sprint (\%)} =\frac{P_{a}}{P_{t}} \times 100
```suggestion
        \text{Parole inserite nel glossario ad ogni sprint (\%)} =\frac{P_{a}}{P_{t}} \times 100 
```

2024-05-29 08:49 UTC, LewentalDigital approved these changes

2024-05-29 10:04 UTC, stoccotommaso02 requested changes
@LewentalDigital su una review di ieri mattina ho appuntato alcune discrepanze tra le NdP di questa PR e il PdQ che abbiamo valutato ieri. Sono alcune metriche che evidentemente erano state rimosse nel processo di valutazione ma non in questo documento, tranne l'ultima che invece è presente nel PdQ ma non qui (forse andrà tolta da lì)

> Metriche in più sulle NdP rispetto al PdQ:
>
>  - modified condition/decision coverage (M.1.2)
>  - Functional size measurement (M.1.5)
>  - Accuratezza rispetto alle attese (M.1.6)
>  - MANCANTE (o reindirizzato?): Impatto delle modifiche (M.1.12 nel PdQ)

2024-05-29 20:57 UTC, LewentalDigital requested changes
- [ ] Rimuovere M.1.2 Modified condition/decision coverage
- [ ] Rimuovere M.1.5 Functional Size Measurement
- [ ] Rimuovere M.1.6 Accuratezza rispetto alle attese

2024-05-30 12:14 UTC, Rikicavaz77 commented
> Sì, ne ho parlato ieri dopo la riunione con @martinaamico , creaiamo una issue per fare modifiche nel PDQ?

@LewentalDigital le modifiche che hai richiesto quanto sono ampie?

2024-05-31 12:23 UTC, LewentalDigital commented
> > Sì, ne ho parlato ieri dopo la riunione con @martinaamico , creaiamo una issue per fare modifiche nel PDQ?
> 
> @LewentalDigital le modifiche che hai richiesto quanto sono ampie?

Poco, si tratta do modificare qualche riga della tabella delle metriche

2024-05-31 12:25 UTC, Rikicavaz77 commented
> Poco, si tratta do modificare qualche riga della tabella delle metriche

Perfetto, vuoi farlo direttamente tu? Visto che Martina ora non ha più il ruolo di amminstratore.

2024-06-01 16:25 UTC, LewentalDigital approved these changes

2024-06-01 16:27 UTC, LewentalDigital commented
Fixato le metriche allineandole a quelle del PdQ
Farò una PR separata per le modifiche discusse l'altro giorno

2024-06-01 16:28 UTC, Rikicavaz77 approved these changes
LGTM

2024-06-01 18:45 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_10.tex
> +        \item $N_{a}$: Risposta attesa.
```suggestion
        \item $R_{a}$: Risposta attesa.
```

2024-06-01 18:45 UTC, LewentalDigital commented on sources/documents/2_RTB/NormeDiProgetto/Accertamento_qualita/Metriche/metriche_M1/M_1_10.tex
> +    \item \textbf{Misurazione}: L'accuratezza della risposta è misurata in base alla distanza della risposta ottenuta dopo la generazione di un prompt su frasi preselezionate e la risposta attesa scr
```suggestion
    \item \textbf{Misurazione}: L'accuratezza della risposta è misurata in base alla distanza della risposta ottenuta dopo la generazione di un prompt su frasi preselezionate e la risposta attesa scritta dall'attore tecnico nel dizionario dati. Questa percentuale l'abbiamo calcolata come :
```

2024-06-03 13:06 UTC, merged