Verbale interno 2024-05-23
Argo-swe/Docs pull request #87
Opened 2024-05-26 13:23 UTC by RaulPianon

[ARGO-55]

2024-05-26 17:00 UTC, Rikicavaz77 commented
@CristoMarco prendo io in carico la review della pull request.

2024-05-28 06:31 UTC, Rikicavaz77 requested changes

2024-05-28 06:31 UTC, Rikicavaz77 commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/todo.tex
>      \hline ARGO-64 & Modifica del file IndexManager & \tommaso, \martina, \riccardo & 2024-05-28 \\
Direi di non inserire tutte le attività nel verbale, ma di selezionare solo quelle legate agli argomenti discussi durante la riunione. Inoltre, alcune attività devono essere inserite nel verbale esterno.

2024-05-28 06:45 UTC, Rikicavaz77 commented
Ho fatto un commit qui per modificare il todo del verbale del 7 maggio, perché alcune attività andavano segnate nel verbale esterno del giorno prima.

2024-05-28 06:51 UTC, Rikicavaz77 commented
@RaulPianon Dentro questa pull request, riusciresti a ricaricare il capitolo riunione con alcune modifiche? Perché di solito noi i verbali interni li scriviamo sempre al passato.

2024-05-28 06:52 UTC, Rikicavaz77 commented
Inoltre, il 23 maggio era già iniziato lo sprint 4, quindi il responsabile è @CristoMarco.

2024-05-29 14:09 UTC, Rikicavaz77 requested changes

2024-05-29 19:33 UTC, RaulPianon commented on sources/documents/2_RTB/Verbali/Interni/VerbaleInterno_2024-05-23/capitolo-riunione.tex
>  \subsection{Discussione e decisioni}
Non ho capito se qua c'è una qualche modifica che hai cancellato o se è da sistemare il termine con "sprint backlog"

2024-05-30 15:48 UTC, CristoMarco approved these changes
Mi pare ci sia tutto

2024-05-30 15:57 UTC, Rikicavaz77 commented
@CristoMarco se vuoi puoi caricare la firma per l'approvazione, poi ci ridò una letta veloce.

2024-06-05 14:31 UTC, merged